// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        VL_OUT8(io_debug_stall,0,0);
        VL_OUT8(io_debug_lsu1_is_load,0,0);
        VL_OUT8(io_debug_lsu1_is_store,0,0);
        VL_OUT8(io_debug_lsu1_store_mask,3,0);
        VL_OUT8(io_debug_lsu2_is_load,0,0);
        VL_OUT8(io_debug_lsu2_is_store,0,0);
        VL_OUT8(io_debug_lsu2_store_mask,3,0);
        VL_OUT8(io_debug_wbu_valid1,0,0);
        VL_OUT8(io_debug_wbu_valid2,0,0);
        VL_OUT8(io_debug_wbu_conflict,0,0);
        VL_OUT8(io_debug_wbu_rd1,4,0);
        VL_OUT8(io_debug_wbu_rd2,4,0);
        VL_OUT8(io_debug_wbu_wr1_addr,4,0);
        VL_OUT8(io_debug_wbu_wr2_addr,4,0);
        VL_OUT8(io_debug_grf_rden,0,0);
        VL_OUT8(io_debug_grf_rdaddr,4,0);
        CData/*4:0*/ top__DOT___wbu_io_wbu_to_grf_wr1_addr;
        CData/*4:0*/ top__DOT___wbu_io_wbu_to_grf_wr2_addr;
        CData/*4:0*/ top__DOT___lsu2_io_lsu_to_wbu_rd;
        CData/*3:0*/ top__DOT___lsu2_io_lsu_to_dmem_mask;
        CData/*0:0*/ top__DOT___lsu2_io_lsu_to_dmem_wen;
        CData/*0:0*/ top__DOT___lsu2_io_lsu_to_dmem_ren;
        CData/*4:0*/ top__DOT___lsu1_io_lsu_to_wbu_rd;
        CData/*3:0*/ top__DOT___lsu1_io_lsu_to_dmem_mask;
        CData/*0:0*/ top__DOT___lsu1_io_lsu_to_dmem_wen;
        CData/*0:0*/ top__DOT___lsu1_io_lsu_to_dmem_ren;
        CData/*0:0*/ top__DOT___exu2_io_exu_to_lsu_op_is_lb;
        CData/*0:0*/ top__DOT___exu2_io_exu_to_lsu_op_is_lh;
        CData/*0:0*/ top__DOT___exu2_io_exu_to_lsu_op_is_lw;
        CData/*0:0*/ top__DOT___exu2_io_exu_to_lsu_op_is_lbu;
        CData/*0:0*/ top__DOT___exu2_io_exu_to_lsu_op_is_lhu;
        CData/*0:0*/ top__DOT___exu2_io_exu_to_lsu_op_is_sb;
        CData/*0:0*/ top__DOT___exu2_io_exu_to_lsu_op_is_sh;
        CData/*0:0*/ top__DOT___exu2_io_exu_to_lsu_op_is_sw;
        CData/*0:0*/ top__DOT___exu1_io_exu_to_ifu_take_branch;
        CData/*4:0*/ top__DOT___idu_io_idu_to_grf_dec1_redreg_rs1;
        CData/*4:0*/ top__DOT___idu_io_idu_to_grf_dec1_redreg_rs2;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_lui;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_auipc;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_jal;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_jalr;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_beq;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_bne;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_blt;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_bge;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_bltu;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_bgeu;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_addi;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_slti;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_sltiu;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_xori;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_ori;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_andi;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_slli;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_srli;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_srai;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_add;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_sub;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_sll;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_slt;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_sltu;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_xor;
    };
    struct {
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_srl;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_sra;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_or;
        CData/*0:0*/ top__DOT___idu_io_idu_to_exu2_dec2_op_is_and;
        CData/*0:0*/ top__DOT___idu_io_idu_to_ifu_is_stall;
        CData/*4:0*/ top__DOT__idu__DOT___dec2_io_rs1;
        CData/*4:0*/ top__DOT__idu__DOT___dec2_io_rs2;
        CData/*0:0*/ top__DOT__idu__DOT___dec1_io_is_ebreak;
        CData/*4:0*/ top__DOT__idu__DOT___dec1_io_rd;
        CData/*0:0*/ top__DOT__idu__DOT__isLoad2;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_jalr;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_beq;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_bne;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_blt;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_bge;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_bltu;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_bgeu;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_lb;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_lh;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_lw;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_lbu;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_lhu;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_sb;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_sh;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_sw;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_addi;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_slti;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_sltiu;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_xori;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_ori;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_andi;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_slli;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_srli;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_srai;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_add;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_sub;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_sll;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_slt;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_sltu;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_xor;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_srl;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_sra;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_or;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT___instDecoder_io_is_and;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT__instDecoder__DOT____VdfgRegularize_h2df762c6_0_1;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT__instDecoder__DOT____VdfgRegularize_h2df762c6_0_2;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT__instDecoder__DOT____VdfgRegularize_h2df762c6_0_3;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT__instDecoder__DOT____VdfgRegularize_h2df762c6_0_4;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT__infoDecoder__DOT__need_imm_u;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT__infoDecoder__DOT____VdfgRegularize_he37144c4_0_1;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT__infoDecoder__DOT____VdfgRegularize_he37144c4_0_2;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT__infoDecoder__DOT____VdfgRegularize_he37144c4_0_4;
        CData/*0:0*/ top__DOT__idu__DOT__dec1__DOT__infoDecoder__DOT____VdfgRegularize_he37144c4_0_6;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_jalr;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_beq;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_bne;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_blt;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_bge;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_bltu;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_bgeu;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_lb;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_lh;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_lw;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_lbu;
    };
    struct {
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_lhu;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_sb;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_sh;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_sw;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_addi;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_slti;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_sltiu;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_xori;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_ori;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_andi;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_slli;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_srli;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_srai;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_add;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_sub;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_sll;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_slt;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_sltu;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_xor;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_srl;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_sra;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_or;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT___instDecoder_io_is_and;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT__instDecoder__DOT____VdfgRegularize_h2df762c6_0_1;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT__instDecoder__DOT____VdfgRegularize_h2df762c6_0_2;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT__instDecoder__DOT____VdfgRegularize_h2df762c6_0_3;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT__instDecoder__DOT____VdfgRegularize_h2df762c6_0_4;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT__infoDecoder__DOT__need_imm_u;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT__infoDecoder__DOT____VdfgRegularize_he37144c4_0_1;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT__infoDecoder__DOT____VdfgRegularize_he37144c4_0_2;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT__infoDecoder__DOT____VdfgRegularize_he37144c4_0_3;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT__infoDecoder__DOT____VdfgRegularize_he37144c4_0_4;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT__infoDecoder__DOT____VdfgRegularize_he37144c4_0_5;
        CData/*0:0*/ top__DOT__idu__DOT__dec2__DOT__infoDecoder__DOT____VdfgRegularize_he37144c4_0_6;
        CData/*4:0*/ top__DOT__exu1__DOT__shamt;
        CData/*0:0*/ top__DOT__exu1__DOT__is_jump;
        CData/*0:0*/ top__DOT__exu1__DOT__is_branch;
        CData/*0:0*/ top__DOT__exu1__DOT__is_load;
        CData/*0:0*/ top__DOT__exu1__DOT____VdfgRegularize_haeb391f3_0_0;
        CData/*0:0*/ top__DOT__exu1__DOT____VdfgRegularize_haeb391f3_0_1;
        CData/*0:0*/ top__DOT__exu1__DOT____VdfgRegularize_haeb391f3_0_2;
        CData/*4:0*/ top__DOT__exu2__DOT__shamt;
        CData/*0:0*/ top__DOT__exu2__DOT__is_jump;
        CData/*0:0*/ top__DOT__exu2__DOT__is_branch;
        CData/*0:0*/ top__DOT__exu2__DOT__is_load;
        CData/*0:0*/ top__DOT__exu2__DOT____VdfgRegularize_haeb391f3_0_0;
        CData/*0:0*/ top__DOT__exu2__DOT____VdfgRegularize_haeb391f3_0_1;
        CData/*0:0*/ top__DOT__exu2__DOT____VdfgRegularize_haeb391f3_0_2;
        CData/*7:0*/ top__DOT__lsu1__DOT__byte_data;
        CData/*7:0*/ top__DOT__lsu2__DOT__byte_data;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_0;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_1;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_2;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_3;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_4;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_5;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_6;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_7;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_8;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_9;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_10;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_11;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_12;
        CData/*0:0*/ __VdfgRegularize_he50b618e_0_13;
    };
    struct {
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clock__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*15:0*/ top__DOT__lsu1__DOT__halfword_data;
        SData/*15:0*/ top__DOT__lsu2__DOT__halfword_data;
        VL_OUT(io_debug_inst1_pc,31,0);
        VL_OUT(io_debug_inst2_pc,31,0);
        VL_OUT(io_debug_inst1,31,0);
        VL_OUT(io_debug_inst2,31,0);
        VL_OUT(io_debug_exu1_alu_out,31,0);
        VL_OUT(io_debug_exu1_alu_source1,31,0);
        VL_OUT(io_debug_exu1_alu_source2,31,0);
        VL_OUT(io_debug_exu1_agu_out,31,0);
        VL_OUT(io_debug_exu2_alu_out,31,0);
        VL_OUT(io_debug_exu2_alu_source1,31,0);
        VL_OUT(io_debug_exu2_alu_source2,31,0);
        VL_OUT(io_debug_exu2_agu_out,31,0);
        VL_OUT(io_debug_lsu1_addr,31,0);
        VL_OUT(io_debug_lsu1_read_origin,31,0);
        VL_OUT(io_debug_lsu1_final_wb_data,31,0);
        VL_OUT(io_debug_lsu1_store_data_shifted,31,0);
        VL_OUT(io_debug_lsu2_addr,31,0);
        VL_OUT(io_debug_lsu2_read_origin,31,0);
        VL_OUT(io_debug_lsu2_final_wb_data,31,0);
        VL_OUT(io_debug_lsu2_store_data_shifted,31,0);
        VL_OUT(io_debug_grf_regs_0,31,0);
        VL_OUT(io_debug_grf_regs_1,31,0);
        VL_OUT(io_debug_grf_regs_2,31,0);
        VL_OUT(io_debug_grf_regs_3,31,0);
        VL_OUT(io_debug_grf_regs_4,31,0);
        VL_OUT(io_debug_grf_regs_5,31,0);
        VL_OUT(io_debug_grf_regs_6,31,0);
        VL_OUT(io_debug_grf_regs_7,31,0);
        VL_OUT(io_debug_grf_regs_8,31,0);
        VL_OUT(io_debug_grf_regs_9,31,0);
        VL_OUT(io_debug_grf_regs_10,31,0);
        VL_OUT(io_debug_grf_regs_11,31,0);
        VL_OUT(io_debug_grf_regs_12,31,0);
        VL_OUT(io_debug_grf_regs_13,31,0);
        VL_OUT(io_debug_grf_regs_14,31,0);
        VL_OUT(io_debug_grf_regs_15,31,0);
        VL_OUT(io_debug_grf_input,31,0);
        IData/*31:0*/ top__DOT___dmem_io_dmem_to_lsu_1_load_data;
        IData/*31:0*/ top__DOT___dmem_io_dmem_to_lsu_2_load_data;
        IData/*31:0*/ top__DOT___imem_io_imem_to_ifu_inst1;
        IData/*31:0*/ top__DOT___imem_io_imem_to_ifu_inst2;
        IData/*31:0*/ top__DOT___grf_io_grf_to_idu_dec1_value_inst1rs1_value;
        IData/*31:0*/ top__DOT___grf_io_grf_to_idu_dec1_value_inst1rs2_value;
        IData/*31:0*/ top__DOT___grf_io_grf_to_idu_dec2_value_inst2rs1_value;
        IData/*31:0*/ top__DOT___wbu_io_wbu_to_grf_wr1_data;
        IData/*31:0*/ top__DOT___wbu_io_wbu_to_grf_wr2_data;
        IData/*31:0*/ top__DOT___lsu2_io_lsu_to_dmem_addr;
        IData/*31:0*/ top__DOT___lsu2_io_lsu_to_dmem_store_data;
        IData/*31:0*/ top__DOT___lsu1_io_lsu_to_dmem_addr;
        IData/*31:0*/ top__DOT___lsu1_io_lsu_to_dmem_store_data;
        IData/*31:0*/ top__DOT___exu2_io_exu_to_lsu_data_store_data;
        IData/*31:0*/ top__DOT___exu2_io_exu_to_lsu_exu_through_lsu_to_wbu_grf_wb_data;
        IData/*31:0*/ top__DOT___exu1_io_exu_to_lsu_exu_through_lsu_to_wbu_grf_wb_data;
        IData/*31:0*/ top__DOT___idu_io_idu_to_exu1_dec1_val_nextpc;
        IData/*31:0*/ top__DOT___idu_io_idu_to_exu2_dec2_imm;
        IData/*31:0*/ top__DOT___idu_io_idu_to_exu2_dec2_val_rs1_val;
        IData/*31:0*/ top__DOT___idu_io_idu_to_exu2_dec2_val_nextpc;
    };
    struct {
        IData/*31:0*/ top__DOT___ifu_io_ifu_to_idu_inst2_nextpc;
        IData/*31:0*/ top__DOT__ifu__DOT__pcReg;
        IData/*31:0*/ top__DOT__idu__DOT___dec2_io_imm;
        IData/*31:0*/ top__DOT__idu__DOT___dec1_io_imm;
        IData/*31:0*/ top__DOT__exu1__DOT___target_branch_T;
        IData/*31:0*/ top__DOT__exu2__DOT___target_branch_T;
        IData/*31:0*/ top__DOT__grf__DOT__regs_0;
        IData/*31:0*/ top__DOT__grf__DOT__regs_1;
        IData/*31:0*/ top__DOT__grf__DOT__regs_2;
        IData/*31:0*/ top__DOT__grf__DOT__regs_3;
        IData/*31:0*/ top__DOT__grf__DOT__regs_4;
        IData/*31:0*/ top__DOT__grf__DOT__regs_5;
        IData/*31:0*/ top__DOT__grf__DOT__regs_6;
        IData/*31:0*/ top__DOT__grf__DOT__regs_7;
        IData/*31:0*/ top__DOT__grf__DOT__regs_8;
        IData/*31:0*/ top__DOT__grf__DOT__regs_9;
        IData/*31:0*/ top__DOT__grf__DOT__regs_10;
        IData/*31:0*/ top__DOT__grf__DOT__regs_11;
        IData/*31:0*/ top__DOT__grf__DOT__regs_12;
        IData/*31:0*/ top__DOT__grf__DOT__regs_13;
        IData/*31:0*/ top__DOT__grf__DOT__regs_14;
        IData/*31:0*/ top__DOT__grf__DOT__regs_15;
        VlWide<16>/*511:0*/ top__DOT__grf__DOT___GEN;
        IData/*31:0*/ __Vfunc_top__DOT__imem__DOT__memory__DOT__pmem_read__0__Vfuncout;
        IData/*31:0*/ __Vfunc_top__DOT__imem__DOT__memory__DOT__pmem_read__1__Vfuncout;
        IData/*31:0*/ __Vfunc_top__DOT__dmem__DOT__memory__DOT__pmem_read__2__Vfuncout;
        IData/*31:0*/ __Vfunc_top__DOT__dmem__DOT__memory__DOT__pmem_read__3__Vfuncout;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
