/* Generated by Yosys 0.62+117 (git sha1 1d3f9b790, clang++ 18.1.8 -fPIC -O3) */

(* hdlname = "counter" *)
(* top =  1  *)
(* src = "counter.v:2.1-12.10" *)
module counter(clk, rst, en, \count[0] , \count[1] );
  (* src = "counter.v:3.9-3.12" *)
  input clk;
  wire clk;
  (* src = "counter.v:4.9-4.12" *)
  input rst;
  wire rst;
  (* src = "counter.v:5.9-5.11" *)
  input en;
  wire en;
  (* src = "counter.v:6.20-6.25" *)
  output \count[0] ;
  wire \count[0] ;
  (* src = "counter.v:6.20-6.25" *)
  output \count[1] ;
  wire \count[1] ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  NOT _10_ (
    .A(rst),
    .Y(_07_)
  );
  NAND _11_ (
    .A(\count[0] ),
    .B(en),
    .Y(_08_)
  );
  NAND _12_ (
    .A(\count[1] ),
    .B(_08_),
    .Y(_09_)
  );
  NOT _13_ (
    .A(_09_),
    .Y(_02_)
  );
  NOR _14_ (
    .A(\count[1] ),
    .B(_08_),
    .Y(_03_)
  );
  NOR _15_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  NOR _16_ (
    .A(rst),
    .B(_04_),
    .Y(_00_)
  );
  NOR _17_ (
    .A(\count[0] ),
    .B(en),
    .Y(_05_)
  );
  NAND _18_ (
    .A(_07_),
    .B(_08_),
    .Y(_06_)
  );
  NOR _19_ (
    .A(_05_),
    .B(_06_),
    .Y(_01_)
  );
  (* src = "counter.v:8.3-11.6" *)
  DFF _20_ (
    .C(clk),
    .D(_00_),
    .Q(\count[1] )
  );
  (* src = "counter.v:8.3-11.6" *)
  DFF _21_ (
    .C(clk),
    .D(_01_),
    .Q(\count[0] )
  );
endmodule
