// Generated by CIRCT firtool-1.139.0
module Comparator(
  input        io_en,
  input  [7:0] io_r0,
               io_rs2,
  output       io_out2jalmux
);

  assign io_out2jalmux = io_en & io_r0 != io_rs2;
endmodule

