// Generated by CIRCT firtool-1.139.0
module GRF(
  input        clock,
               reset,
               io_rst,
               io_rden,
               io_out1en,
               io_out2en,
               io_immen,
  input  [3:0] io_imm,
  input  [1:0] io_out1addr,
               io_out2addr,
               io_inaddr,
  input  [7:0] io_din,
  output [7:0] io_out1,
               io_out2,
               io_r0,
               io_r2
);

  reg  [7:0]      regs_0;
  reg  [7:0]      regs_1;
  reg  [7:0]      regs_2;
  reg  [7:0]      regs_3;
  wire [3:0][7:0] _GEN = {{regs_3}, {regs_2}, {regs_1}, {regs_0}};
  always @(posedge clock) begin
    if (reset) begin
      regs_0 <= 8'h0;
      regs_1 <= 8'h0;
      regs_2 <= 8'h0;
      regs_3 <= 8'h0;
    end
    else if (io_rst) begin
      regs_0 <= 8'h0;
      regs_1 <= 8'h0;
      regs_2 <= 8'h0;
      regs_3 <= 8'h0;
    end
    else begin
      automatic logic [7:0] writeData;
      writeData = io_immen ? {4'h0, io_imm} : io_din;
      if (io_rden & io_inaddr == 2'h0)
        regs_0 <= writeData;
      if (io_rden & io_inaddr == 2'h1)
        regs_1 <= writeData;
      if (io_rden & io_inaddr == 2'h2)
        regs_2 <= writeData;
      if (io_rden & (&io_inaddr))
        regs_3 <= writeData;
    end
  end // always @(posedge)
  assign io_out1 = io_out1en ? _GEN[io_out1addr] : 8'h0;
  assign io_out2 = io_out2en ? _GEN[io_out2addr] : 8'h0;
  assign io_r0 = regs_0;
  assign io_r2 = regs_2;
endmodule

