// Generated by CIRCT firtool-1.139.0
module IDU(
  input  [7:0] io_instruction,
  output       io_rden,
               io_rs1en,
               io_rs2en,
               io_addren,
               io_immen,
  output [1:0] io_rd,
               io_rs1,
               io_rs2,
  output [3:0] io_addr,
               io_imm
);

  wire isAdd = io_instruction[7:6] == 2'h0;
  wire isLi = io_instruction[7:6] == 2'h2;
  assign io_rden = isAdd | isLi;
  assign io_rs1en = isAdd;
  assign io_rs2en = isAdd | (&(io_instruction[7:6]));
  assign io_addren = &(io_instruction[7:6]);
  assign io_immen = isLi;
  assign io_rd = io_instruction[5:4];
  assign io_rs1 = io_instruction[3:2];
  assign io_rs2 = io_instruction[1:0];
  assign io_addr = io_instruction[5:2];
  assign io_imm = io_instruction[3:0];
endmodule

