// Generated by CIRCT firtool-1.139.0
module PC(
  input        clock,
               reset,
               io_rst,
               io_jalmux,
  input  [3:0] io_jal2mux,
  output [3:0] io_pc2romaddr
);

  reg [3:0] pcReg;
  always @(posedge clock) begin
    if (reset)
      pcReg <= 4'h0;
    else
      pcReg <= io_rst ? 4'h0 : io_jalmux ? io_jal2mux : pcReg + 4'h1;
  end // always @(posedge)
  assign io_pc2romaddr = pcReg;
endmodule

