// Generated by CIRCT firtool-1.139.0
module ROM(
  input  [3:0] io_romaddr,
  output [7:0] io_instruction
);

  wire [15:0][7:0] _GEN =
    '{8'h0,
      8'h0,
      8'h0,
      8'h0,
      8'h0,
      8'h0,
      8'h0,
      8'h0,
      8'hDF,
      8'hD1,
      8'h29,
      8'h17,
      8'hB1,
      8'hA0,
      8'h90,
      8'h8A};
  assign io_instruction = _GEN[io_romaddr];
endmodule

