// Generated by CIRCT firtool-1.139.0
module top(
  input        clock,
               reset,
               io_clk,
               io_rst,
  output [7:0] io_led
);

  wire       _comp_mod_io_out2jalmux;
  wire [7:0] _alu_mod_io_out;
  wire [7:0] _grf_mod_io_out1;
  wire [7:0] _grf_mod_io_out2;
  wire [7:0] _grf_mod_io_r0;
  wire       _idu_mod_io_rden;
  wire       _idu_mod_io_rs1en;
  wire       _idu_mod_io_rs2en;
  wire       _idu_mod_io_addren;
  wire       _idu_mod_io_immen;
  wire [1:0] _idu_mod_io_rd;
  wire [1:0] _idu_mod_io_rs1;
  wire [1:0] _idu_mod_io_rs2;
  wire [3:0] _idu_mod_io_addr;
  wire [3:0] _idu_mod_io_imm;
  wire [7:0] _rom_mod_io_instruction;
  wire [3:0] _pc_mod_io_pc2romaddr;
  PC pc_mod (
    .clock         (clock),
    .reset         (reset),
    .io_rst        (io_rst),
    .io_jalmux     (_comp_mod_io_out2jalmux),
    .io_jal2mux    (_idu_mod_io_addr),
    .io_pc2romaddr (_pc_mod_io_pc2romaddr)
  );
  ROM rom_mod (
    .io_romaddr     (_pc_mod_io_pc2romaddr),
    .io_instruction (_rom_mod_io_instruction)
  );
  IDU idu_mod (
    .io_instruction (_rom_mod_io_instruction),
    .io_rden        (_idu_mod_io_rden),
    .io_rs1en       (_idu_mod_io_rs1en),
    .io_rs2en       (_idu_mod_io_rs2en),
    .io_addren      (_idu_mod_io_addren),
    .io_immen       (_idu_mod_io_immen),
    .io_rd          (_idu_mod_io_rd),
    .io_rs1         (_idu_mod_io_rs1),
    .io_rs2         (_idu_mod_io_rs2),
    .io_addr        (_idu_mod_io_addr),
    .io_imm         (_idu_mod_io_imm)
  );
  GRF grf_mod (
    .clock       (clock),
    .reset       (reset),
    .io_rst      (io_rst),
    .io_rden     (_idu_mod_io_rden),
    .io_out1en   (_idu_mod_io_rs1en),
    .io_out2en   (_idu_mod_io_rs2en),
    .io_immen    (_idu_mod_io_immen),
    .io_imm      (_idu_mod_io_imm),
    .io_out1addr (_idu_mod_io_rs1),
    .io_out2addr (_idu_mod_io_rs2),
    .io_inaddr   (_idu_mod_io_rd),
    .io_din      (_alu_mod_io_out),
    .io_out1     (_grf_mod_io_out1),
    .io_out2     (_grf_mod_io_out2),
    .io_r0       (_grf_mod_io_r0),
    .io_r2       (io_led)
  );
  Adder8bit alu_mod (
    .io_a   (_grf_mod_io_out1),
    .io_b   (_grf_mod_io_out2),
    .io_out (_alu_mod_io_out)
  );
  Comparator comp_mod (
    .io_en         (_idu_mod_io_addren),
    .io_r0         (_grf_mod_io_r0),
    .io_rs2        (_grf_mod_io_out2),
    .io_out2jalmux (_comp_mod_io_out2jalmux)
  );
endmodule

