// Generated by CIRCT firtool-1.139.0
module InputMUXforAGU(
  input  [31:0] io_inputfromRS1,
                io_inputfromIMM12,
  input         io_add,
                io_addi,
                io_jalr,
                io_lbu,
                io_lw,
                io_lui,
                io_sw,
                io_sb,
  output [31:0] io_source1,
                io_source2
);

  wire _io_source2_T = io_add | io_addi;
  wire _io_source2_T_3 = io_lbu | io_lw;
  assign io_source1 =
    _io_source2_T | io_jalr | io_lui | ~(_io_source2_T_3 | io_sw | io_sb)
      ? 32'h0
      : io_inputfromRS1;
  assign io_source2 =
    _io_source2_T | io_jalr | io_lui | ~(_io_source2_T_3 | io_sw | io_sb)
      ? 32'h0
      : io_inputfromIMM12;
endmodule

