// Generated by CIRCT firtool-1.139.0
module AddrPassthrough(
  input  [4:0] io_rs1_addr_in,
               io_rs2_addr_in,
  output [4:0] io_rs1_addr_out,
               io_rs2_addr_out
);

  assign io_rs1_addr_out = io_rs1_addr_in;
  assign io_rs2_addr_out = io_rs2_addr_in;
endmodule

