// Generated by CIRCT firtool-1.139.0
module ALU(
  input  [31:0] io_source1,
                io_source2,
  input  [3:0]  io_alu_op,
  output [31:0] io_output
);

  wire [62:0]       _io_output_T_7 = {31'h0, io_source1} << io_source2[4:0];
  wire [31:0]       _GEN = {27'h0, io_source2[4:0]};
  wire [15:0][31:0] _GEN_0 =
    {{32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {32'h0},
     {io_source2},
     {io_source1 & io_source2},
     {io_source1 | io_source2},
     {$signed($signed(io_source1) >>> _GEN)},
     {io_source1 >> _GEN},
     {io_source1 ^ io_source2},
     {{31'h0, io_source1 < io_source2}},
     {{31'h0, $signed(io_source1) < $signed(io_source2)}},
     {_io_output_T_7[31:0]},
     {io_source1 - io_source2},
     {32'h0}};
  assign io_output = io_alu_op == 4'h0 ? io_source1 + io_source2 : _GEN_0[io_alu_op];
endmodule

