// Generated by CIRCT firtool-1.139.0
module BRU(
  input  [31:0] io_source1,
                io_source2,
  output [31:0] io_output
);

  wire [31:0] _io_output_T = io_source1 + io_source2;
  assign io_output = {_io_output_T[31:2], 2'h0};
endmodule

