// Generated by CIRCT firtool-1.139.0
module BRU(
  input  [31:0] io_rs1_data,
                io_rs2_data,
  input  [2:0]  io_branch_type,
  input         io_jalr,
  input  [31:0] io_imm_b,
                io_imm_i,
                io_current_pc,
  output        io_take_branch,
  output [31:0] io_target
);

  wire        _branch_cond_T_9 = (&io_branch_type) & io_rs1_data >= io_rs2_data;
  wire [7:0]  _GEN =
    {{_branch_cond_T_9},
     {io_rs1_data < io_rs2_data},
     {$signed(io_rs1_data) >= $signed(io_rs2_data)},
     {$signed(io_rs1_data) < $signed(io_rs2_data)},
     {_branch_cond_T_9},
     {_branch_cond_T_9},
     {io_rs1_data != io_rs2_data},
     {io_rs1_data == io_rs2_data}};
  wire [31:0] _io_target_T = io_rs1_data + io_imm_i;
  assign io_take_branch = io_jalr | _GEN[io_branch_type];
  assign io_target = io_jalr ? {_io_target_T[31:2], 2'h0} : io_current_pc + io_imm_b;
endmodule

