// Generated by CIRCT firtool-1.139.0
module CSR(
  input         clock,
                reset,
  input  [11:0] io_csr_addr,
  output [31:0] io_csr_rdata,
  input         io_csr_wen,
  input  [11:0] io_csr_waddr,
  input  [2:0]  io_csr_op,
  input  [31:0] io_rs1_val,
  input         io_use_imm,
                io_ecall,
                io_is_ebreak,
  input  [31:0] io_current_pc,
  output        io_take_trap,
  output [31:0] io_trap_pc,
  input         io_inst_retire,
  output [31:0] io_debug_mepc
);

  reg  [63:0] mcycle_reg;
  reg  [63:0] minstret_reg;
  reg  [31:0] mstatus_reg;
  reg  [31:0] mtvec_reg;
  reg  [31:0] mepc_reg;
  reg  [31:0] mcause_reg;
  reg  [31:0] mtval_reg;
  reg  [31:0] mie_reg;
  reg  [31:0] mip_reg;
  wire [31:0] io_csr_rdata_0 =
    io_csr_addr == 12'h300
      ? mstatus_reg
      : io_csr_addr == 12'h301
          ? 32'h0
          : io_csr_addr == 12'h304
              ? mie_reg
              : io_csr_addr == 12'h305
                  ? mtvec_reg
                  : io_csr_addr == 12'h340
                      ? 32'h0
                      : io_csr_addr == 12'h341
                          ? mepc_reg
                          : io_csr_addr == 12'h342
                              ? mcause_reg
                              : io_csr_addr == 12'h343
                                  ? mtval_reg
                                  : io_csr_addr == 12'h344
                                      ? mip_reg
                                      : io_csr_addr == 12'hB00
                                          ? mcycle_reg[31:0]
                                          : io_csr_addr == 12'hB80
                                              ? mcycle_reg[63:32]
                                              : io_csr_addr == 12'hB02
                                                  ? minstret_reg[31:0]
                                                  : io_csr_addr == 12'hB82
                                                      ? minstret_reg[63:32]
                                                      : io_csr_addr == 12'hF11
                                                          ? 32'h79737978
                                                          : io_csr_addr == 12'hF12
                                                              ? 32'h18A9E3B
                                                              : 32'h0;
  always @(posedge clock) begin
    if (reset) begin
      mcycle_reg <= 64'h0;
      minstret_reg <= 64'h0;
      mstatus_reg <= 32'h1800;
      mtvec_reg <= 32'h0;
      mepc_reg <= 32'h0;
      mcause_reg <= 32'h0;
      mtval_reg <= 32'h0;
      mie_reg <= 32'h0;
      mip_reg <= 32'h0;
    end
    else begin
      automatic logic [31:0] t_rs1 = io_use_imm ? {27'h0, io_rs1_val[4:0]} : io_rs1_val;
      automatic logic [31:0] csr_write_val;
      automatic logic        _GEN;
      automatic logic        _GEN_0;
      automatic logic        _GEN_1;
      automatic logic        _GEN_2;
      automatic logic        _GEN_3;
      automatic logic        _GEN_4;
      automatic logic        _GEN_5;
      csr_write_val =
        io_csr_op == 3'h0
          ? t_rs1
          : io_csr_op == 3'h1
              ? io_csr_rdata_0 | t_rs1
              : io_csr_op == 3'h2 ? io_csr_rdata_0 & ~t_rs1 : 32'h0;
      _GEN = io_csr_waddr == 12'h300;
      _GEN_0 = io_csr_waddr == 12'h304;
      _GEN_1 = io_csr_waddr == 12'h305;
      _GEN_2 = io_csr_waddr == 12'h340;
      _GEN_3 = io_csr_waddr == 12'h341;
      _GEN_4 = io_csr_waddr == 12'h342;
      _GEN_5 = io_csr_waddr == 12'h343;
      mcycle_reg <= mcycle_reg + 64'h1;
      if (io_inst_retire)
        minstret_reg <= minstret_reg + 64'h1;
      if (io_csr_wen & _GEN)
        mstatus_reg <= csr_write_val;
      if (~io_csr_wen | _GEN | _GEN_0 | ~_GEN_1) begin
      end
      else
        mtvec_reg <= csr_write_val;
      if (io_is_ebreak) begin
        mepc_reg <= io_current_pc;
        mcause_reg <= 32'h3;
        mtval_reg <= io_current_pc;
      end
      else if (io_ecall) begin
        mepc_reg <= io_current_pc + 32'h4;
        mcause_reg <= 32'hB;
        mtval_reg <= 32'h0;
      end
      else begin
        if (~io_csr_wen | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | ~_GEN_3) begin
        end
        else
          mepc_reg <= csr_write_val;
        if (~io_csr_wen | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | ~_GEN_4) begin
        end
        else
          mcause_reg <= csr_write_val;
        if (~io_csr_wen | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4
            | ~_GEN_5) begin
        end
        else
          mtval_reg <= csr_write_val;
      end
      if (~io_csr_wen | _GEN | ~_GEN_0) begin
      end
      else
        mie_reg <= csr_write_val;
      if (~io_csr_wen | _GEN | _GEN_0 | _GEN_1 | _GEN_2 | _GEN_3 | _GEN_4 | _GEN_5
          | io_csr_waddr != 12'h344) begin
      end
      else
        mip_reg <= csr_write_val;
    end
  end // always @(posedge)
  assign io_csr_rdata = io_csr_rdata_0;
  assign io_take_trap = io_is_ebreak | io_ecall;
  assign io_trap_pc = mtvec_reg;
  assign io_debug_mepc = mepc_reg;
endmodule

