// Generated by CIRCT firtool-1.139.0
module dmem(
  input         clock,
  output [31:0] io_dmem_to_lsu_1_load_data,
                io_dmem_to_lsu_2_load_data,
  input  [31:0] io_lsu_to_dmem_1_addr,
                io_lsu_to_dmem_1_store_data,
  input  [3:0]  io_lsu_to_dmem_1_mask,
  input         io_lsu_to_dmem_1_wen,
                io_lsu_to_dmem_1_ren,
  input  [31:0] io_lsu_to_dmem_2_addr,
                io_lsu_to_dmem_2_store_data,
  input  [3:0]  io_lsu_to_dmem_2_mask,
  input         io_lsu_to_dmem_2_wen,
                io_lsu_to_dmem_2_ren,
                io_ebreak
);

  DPI_Memory memory (
    .io_clk (clock),
    .wen    (io_lsu_to_dmem_1_wen | io_lsu_to_dmem_2_wen),
    .waddr  (io_lsu_to_dmem_1_wen ? io_lsu_to_dmem_1_addr : io_lsu_to_dmem_2_addr),
    .wdata
      (io_lsu_to_dmem_1_wen ? io_lsu_to_dmem_1_store_data : io_lsu_to_dmem_2_store_data),
    .wmask  (io_lsu_to_dmem_1_wen ? io_lsu_to_dmem_1_mask : io_lsu_to_dmem_2_mask),
    .ren1   (io_lsu_to_dmem_1_ren),
    .raddr1 (io_lsu_to_dmem_1_addr),
    .rdata1 (io_dmem_to_lsu_1_load_data),
    .ren2   (io_lsu_to_dmem_2_ren),
    .raddr2 (io_lsu_to_dmem_2_addr),
    .rdata2 (io_dmem_to_lsu_2_load_data),
    .ebreak (io_ebreak)
  );
endmodule

