// Generated by CIRCT firtool-1.139.0
module EXU(
  input         io_is_add,
                io_is_addi,
                io_is_jalr,
                io_is_lui,
                io_is_lbu,
                io_is_lw,
                io_is_sw,
                io_is_sb,
  input  [4:0]  io_rs1_addr,
                io_rs2_addr,
                io_rd_addr,
  input  [31:0] io_rs1_data,
                io_rs2_data,
                io_imm12,
  output        io_rs1_en,
                io_rs2_en,
  output [31:0] io_agu_addr,
                io_store_data,
                io_alu_result,
  output [4:0]  io_rd_out,
  output        io_jalr_out,
  output [31:0] io_bru_target,
  output [4:0]  io_rs1_addr_out,
                io_rs2_addr_out
);

  wire [31:0] _bruMux_io_source1;
  wire [31:0] _bruMux_io_source2;
  wire [31:0] _aguMux_io_source1;
  wire [31:0] _aguMux_io_source2;
  wire [31:0] _aluMux_io_source1;
  wire [31:0] _aluMux_io_source2;
  AddrPassthrough addrPass (
    .io_rs1_addr_in  (io_rs1_addr),
    .io_rs2_addr_in  (io_rs2_addr),
    .io_rs1_addr_out (io_rs1_addr_out),
    .io_rs2_addr_out (io_rs2_addr_out)
  );
  InputMUXforGRF grfCtrl (
    .io_add   (io_is_add),
    .io_addi  (io_is_addi),
    .io_jalr  (io_is_jalr),
    .io_lbu   (io_is_lbu),
    .io_lw    (io_is_lw),
    .io_sw    (io_is_sw),
    .io_sb    (io_is_sb),
    .io_rs1en (io_rs1_en),
    .io_rs2en (io_rs2_en)
  );
  InputMUXforALU aluMux (
    .io_inputfromRS1   (io_rs1_data),
    .io_inputfromRS2   (io_rs2_data),
    .io_inputfromIMM12 (io_imm12),
    .io_add            (io_is_add),
    .io_addi           (io_is_addi),
    .io_source1        (_aluMux_io_source1),
    .io_source2        (_aluMux_io_source2)
  );
  ALU alu (
    .io_source1 (_aluMux_io_source1),
    .io_source2 (_aluMux_io_source2),
    .io_output  (io_alu_result)
  );
  InputMUXforAGU aguMux (
    .io_inputfromRS1   (io_rs1_data),
    .io_inputfromIMM12 (io_imm12),
    .io_add            (io_is_add),
    .io_addi           (io_is_addi),
    .io_jalr           (io_is_jalr),
    .io_lbu            (io_is_lbu),
    .io_lw             (io_is_lw),
    .io_lui            (io_is_lui),
    .io_sw             (io_is_sw),
    .io_sb             (io_is_sb),
    .io_source1        (_aguMux_io_source1),
    .io_source2        (_aguMux_io_source2)
  );
  AGU agu (
    .io_source1 (_aguMux_io_source1),
    .io_source2 (_aguMux_io_source2),
    .io_output  (io_agu_addr)
  );
  InputMUXforBRU bruMux (
    .io_inputfromRS1   (io_rs1_data),
    .io_inputfromIMM12 (io_imm12),
    .io_add            (io_is_add),
    .io_addi           (io_is_addi),
    .io_jalr           (io_is_jalr),
    .io_lbu            (io_is_lbu),
    .io_lw             (io_is_lw),
    .io_sw             (io_is_sw),
    .io_sb             (io_is_sb),
    .io_source1        (_bruMux_io_source1),
    .io_source2        (_bruMux_io_source2)
  );
  BRU bru (
    .io_source1 (_bruMux_io_source1),
    .io_source2 (_bruMux_io_source2),
    .io_output  (io_bru_target)
  );
  assign io_store_data = io_rs2_data;
  assign io_rd_out = io_rd_addr;
  assign io_jalr_out = io_is_jalr;
endmodule

