// Generated by CIRCT firtool-1.139.0
module EXU(
  input         io_is_lui,
                io_is_auipc,
                io_is_jal,
                io_is_jalr,
                io_is_beq,
                io_is_bne,
                io_is_blt,
                io_is_bge,
                io_is_bltu,
                io_is_bgeu,
                io_is_lb,
                io_is_lh,
                io_is_lw,
                io_is_lbu,
                io_is_lhu,
                io_is_sb,
                io_is_sh,
                io_is_sw,
                io_is_addi,
                io_is_slti,
                io_is_sltiu,
                io_is_xori,
                io_is_ori,
                io_is_andi,
                io_is_slli,
                io_is_srli,
                io_is_srai,
                io_is_add,
                io_is_sub,
                io_is_sll,
                io_is_slt,
                io_is_sltu,
                io_is_xor,
                io_is_srl,
                io_is_sra,
                io_is_or,
                io_is_and,
  input  [4:0]  io_rs1_addr,
                io_rs2_addr,
                io_rd_addr,
  input  [31:0] io_rs1_data,
                io_rs2_data,
                io_imm_i,
                io_imm_s,
                io_imm_b,
                io_imm_u,
                io_imm_j,
                io_current_pc,
  output        io_rs1_en,
                io_rs2_en,
  output [31:0] io_agu_addr,
                io_store_data,
                io_alu_result,
  output [4:0]  io_rd_out,
  output        io_take_branch,
  output [31:0] io_branch_target,
  output [4:0]  io_rs1_addr_out,
                io_rs2_addr_out,
  output [31:0] io_alu_src1,
                io_alu_src2
);

  wire        _bru_io_take_branch;
  wire [31:0] _bru_io_target;
  wire [31:0] _aguMux_io_source1;
  wire [31:0] _aguMux_io_source2;
  wire [31:0] _aluMux_io_source1;
  wire [31:0] _aluMux_io_source2;
  wire        use_rs1 =
    io_is_jalr | io_is_beq | io_is_bne | io_is_blt | io_is_bge | io_is_bltu | io_is_bgeu
    | io_is_lb | io_is_lh | io_is_lw | io_is_lbu | io_is_lhu | io_is_sb | io_is_sh
    | io_is_sw | io_is_addi | io_is_slti | io_is_sltiu | io_is_xori | io_is_ori
    | io_is_andi | io_is_slli | io_is_srli | io_is_srai | io_is_add | io_is_sub
    | io_is_sll | io_is_slt | io_is_sltu | io_is_xor | io_is_srl | io_is_sra | io_is_or
    | io_is_and;
  wire        _is_branch_T = io_is_beq | io_is_bne;
  AddrPassthrough addrPass (
    .io_rs1_addr_in  (io_rs1_addr),
    .io_rs2_addr_in  (io_rs2_addr),
    .io_rs1_addr_out (io_rs1_addr_out),
    .io_rs2_addr_out (io_rs2_addr_out)
  );
  InputMUXforGRF grfCtrl (
    .io_use_rs1 (use_rs1),
    .io_use_rs2
      (_is_branch_T | io_is_blt | io_is_bge | io_is_bltu | io_is_bgeu | io_is_sb
       | io_is_sh | io_is_sw | io_is_add | io_is_sub | io_is_sll | io_is_slt | io_is_sltu
       | io_is_xor | io_is_srl | io_is_sra | io_is_or | io_is_and),
    .io_rs1en   (io_rs1_en),
    .io_rs2en   (io_rs2_en)
  );
  InputMUXforALU aluMux (
    .io_inputfromRS1 (io_rs1_data),
    .io_inputfromRS2 (io_rs2_data),
    .io_inputfromIMM (io_imm_i),
    .io_inputfromU   (io_imm_u),
    .io_current_pc   (io_current_pc),
    .io_is_auipc     (io_is_auipc),
    .io_use_rs1      (use_rs1 & ~io_is_sb & ~io_is_sh & ~io_is_sw & ~io_is_auipc),
    .io_use_rs2
      (io_is_add | io_is_sub | io_is_sll | io_is_slt | io_is_sltu | io_is_xor | io_is_srl
       | io_is_sra | io_is_or | io_is_and),
    .io_use_imm_i
      (io_is_addi | io_is_slti | io_is_sltiu | io_is_xori | io_is_ori | io_is_andi
       | io_is_slli | io_is_srli | io_is_srai | io_is_jalr | io_is_lb | io_is_lh
       | io_is_lw | io_is_lbu | io_is_lhu),
    .io_use_u_imm    (io_is_lui | io_is_auipc),
    .io_source1      (_aluMux_io_source1),
    .io_source2      (_aluMux_io_source2)
  );
  ALU alu (
    .io_source1 (_aluMux_io_source1),
    .io_source2 (_aluMux_io_source2),
    .io_alu_op
      (io_is_add | io_is_addi | io_is_auipc | io_is_jal | io_is_jalr
         ? 4'h0
         : io_is_sub
             ? 4'h1
             : io_is_sll | io_is_slli
                 ? 4'h2
                 : io_is_slt | io_is_slti
                     ? 4'h3
                     : io_is_sltu | io_is_sltiu
                         ? 4'h4
                         : io_is_xor | io_is_xori
                             ? 4'h5
                             : io_is_srl | io_is_srli
                                 ? 4'h6
                                 : io_is_sra | io_is_srai
                                     ? 4'h7
                                     : io_is_or | io_is_ori
                                         ? 4'h8
                                         : io_is_and | io_is_andi
                                             ? 4'h9
                                             : io_is_lui ? 4'hA : 4'h0),
    .io_output  (io_alu_result)
  );
  InputMUXforAGU aguMux (
    .io_inputfromRS1   (io_rs1_data),
    .io_inputfromIMM_I (io_imm_i),
    .io_inputfromIMM_S (io_imm_s),
    .io_is_load        (io_is_lb | io_is_lh | io_is_lw | io_is_lbu | io_is_lhu),
    .io_is_store       (io_is_sb | io_is_sh | io_is_sw),
    .io_source1        (_aguMux_io_source1),
    .io_source2        (_aguMux_io_source2)
  );
  AGU agu (
    .io_source1 (_aguMux_io_source1),
    .io_source2 (_aguMux_io_source2),
    .io_output  (io_agu_addr)
  );
  BRU bru (
    .io_rs1_data    (io_rs1_data),
    .io_rs2_data    (io_rs2_data),
    .io_branch_type
      (io_is_beq
         ? 3'h0
         : io_is_bne
             ? 3'h1
             : io_is_blt ? 3'h4 : io_is_bge ? 3'h5 : io_is_bltu ? 3'h6 : {3{io_is_bgeu}}),
    .io_jalr        (io_is_jalr),
    .io_imm_b       (io_imm_b),
    .io_imm_i       (io_imm_i),
    .io_current_pc  (io_current_pc),
    .io_take_branch (_bru_io_take_branch),
    .io_target      (_bru_io_target)
  );
  assign io_store_data = io_rs2_data;
  assign io_rd_out = io_rd_addr;
  assign io_take_branch =
    io_is_jal | io_is_jalr
    | (_is_branch_T | io_is_blt | io_is_bge | io_is_bltu | io_is_bgeu)
    & _bru_io_take_branch;
  assign io_branch_target = io_is_jal ? io_current_pc + io_imm_j : _bru_io_target;
  assign io_alu_src1 = _aluMux_io_source1;
  assign io_alu_src2 = _aluMux_io_source2;
endmodule

