// Generated by CIRCT firtool-1.139.0
module EXU(
  input         clock,
                reset,
                io_idu_to_exu1_dec1_op_is_lui,
                io_idu_to_exu1_dec1_op_is_auipc,
                io_idu_to_exu1_dec1_op_is_jal,
                io_idu_to_exu1_dec1_op_is_jalr,
                io_idu_to_exu1_dec1_op_is_beq,
                io_idu_to_exu1_dec1_op_is_bne,
                io_idu_to_exu1_dec1_op_is_blt,
                io_idu_to_exu1_dec1_op_is_bge,
                io_idu_to_exu1_dec1_op_is_bltu,
                io_idu_to_exu1_dec1_op_is_bgeu,
                io_idu_to_exu1_dec1_op_is_lb,
                io_idu_to_exu1_dec1_op_is_lh,
                io_idu_to_exu1_dec1_op_is_lw,
                io_idu_to_exu1_dec1_op_is_lbu,
                io_idu_to_exu1_dec1_op_is_lhu,
                io_idu_to_exu1_dec1_op_is_sb,
                io_idu_to_exu1_dec1_op_is_sh,
                io_idu_to_exu1_dec1_op_is_sw,
                io_idu_to_exu1_dec1_op_is_addi,
                io_idu_to_exu1_dec1_op_is_slti,
                io_idu_to_exu1_dec1_op_is_sltiu,
                io_idu_to_exu1_dec1_op_is_xori,
                io_idu_to_exu1_dec1_op_is_ori,
                io_idu_to_exu1_dec1_op_is_andi,
                io_idu_to_exu1_dec1_op_is_slli,
                io_idu_to_exu1_dec1_op_is_srli,
                io_idu_to_exu1_dec1_op_is_srai,
                io_idu_to_exu1_dec1_op_is_add,
                io_idu_to_exu1_dec1_op_is_sub,
                io_idu_to_exu1_dec1_op_is_sll,
                io_idu_to_exu1_dec1_op_is_slt,
                io_idu_to_exu1_dec1_op_is_sltu,
                io_idu_to_exu1_dec1_op_is_xor,
                io_idu_to_exu1_dec1_op_is_srl,
                io_idu_to_exu1_dec1_op_is_sra,
                io_idu_to_exu1_dec1_op_is_or,
                io_idu_to_exu1_dec1_op_is_and,
                io_idu_to_exu1_dec1_op_is_ebreak,
                io_idu_to_exu1_dec1_op_is_csrrw,
                io_idu_to_exu1_dec1_op_is_csrrs,
                io_idu_to_exu1_dec1_op_is_csrrc,
                io_idu_to_exu1_dec1_op_is_csrrwi,
                io_idu_to_exu1_dec1_op_is_csrrsi,
                io_idu_to_exu1_dec1_op_is_csrrci,
                io_idu_to_exu1_dec1_op_is_ecall,
                io_idu_to_exu1_dec1_op_is_mret,
  input  [31:0] io_idu_to_exu1_dec1_imm,
                io_idu_to_exu1_dec1_val_rs1_val,
                io_idu_to_exu1_dec1_val_rs2_val,
                io_idu_to_exu1_dec1_val_nextpc,
  input  [4:0]  io_idu_to_exu1_dec1_rd,
  input         io_idu_to_exu1_is_stall,
  input  [31:0] io_idu_to_exu1_inst1_pc,
                io_idu_to_exu1_inst1,
  output        io_exu_to_lsu_op_is_lb,
                io_exu_to_lsu_op_is_lh,
                io_exu_to_lsu_op_is_lw,
                io_exu_to_lsu_op_is_lbu,
                io_exu_to_lsu_op_is_lhu,
                io_exu_to_lsu_op_is_sb,
                io_exu_to_lsu_op_is_sh,
                io_exu_to_lsu_op_is_sw,
                io_exu_to_lsu_op_is_ebreak,
  output [31:0] io_exu_to_lsu_paddr_addr,
                io_exu_to_lsu_data_store_data,
  output [4:0]  io_exu_to_lsu_exu_through_lsu_to_wbu_rd,
  output [31:0] io_exu_to_lsu_exu_through_lsu_to_wbu_grf_wb_data,
  output        io_exu_to_ifu_take_branch,
  output [31:0] io_exu_to_ifu_branch_target,
  output        io_csr_to_ifu_take_trap,
  output [31:0] io_csr_to_ifu_trap_pc,
  output        io_csr_to_ifu_take_mret,
  output [31:0] io_csr_to_ifu_mret_pc,
  output        io_csr_to_grf_wen,
  output [4:0]  io_csr_to_grf_waddr,
  output [31:0] io_csr_to_grf_wdata,
  output [63:0] io_debug_csr_mcycle,
                io_debug_csr_minstret,
  output [31:0] io_debug_csr_mstatus,
                io_debug_csr_mie,
                io_debug_csr_mtvec,
                io_debug_csr_mepc,
                io_debug_csr_mcause,
                io_debug_csr_mtval,
                io_debug_csr_mip,
                io_debug_alu_out,
                io_debug_alu_source1,
                io_debug_alu_source2,
                io_debug_agu_out
);

  wire [31:0] _csr_io_csr_to_exu_debug_mepc;
  wire        _is_csr_T =
    io_idu_to_exu1_dec1_op_is_csrrw | io_idu_to_exu1_dec1_op_is_csrrs;
  wire        use_imm_csr =
    io_idu_to_exu1_dec1_op_is_csrrwi | io_idu_to_exu1_dec1_op_is_csrrsi
    | io_idu_to_exu1_dec1_op_is_csrrci;
  wire [31:0] _pc_T = io_idu_to_exu1_dec1_val_nextpc - 32'h4;
  wire [4:0]  shamt =
    io_idu_to_exu1_dec1_op_is_slli | io_idu_to_exu1_dec1_op_is_srli
    | io_idu_to_exu1_dec1_op_is_srai
      ? io_idu_to_exu1_dec1_imm[4:0]
      : io_idu_to_exu1_dec1_val_rs2_val[4:0];
  wire [31:0] _target_branch_T = _pc_T + io_idu_to_exu1_dec1_imm;
  wire [62:0] aluOut_sll = {31'h0, io_idu_to_exu1_dec1_val_rs1_val} << shamt;
  wire [31:0] _GEN = {27'h0, shamt};
  wire        is_jump = io_idu_to_exu1_dec1_op_is_jal | io_idu_to_exu1_dec1_op_is_jalr;
  wire [31:0] alu_out =
    io_idu_to_exu1_dec1_op_is_lui
      ? io_idu_to_exu1_dec1_imm
      : io_idu_to_exu1_dec1_op_is_auipc
          ? _target_branch_T
          : io_idu_to_exu1_dec1_op_is_addi | io_idu_to_exu1_dec1_op_is_add
              ? io_idu_to_exu1_dec1_val_rs1_val
                + (io_idu_to_exu1_dec1_op_is_addi
                     ? io_idu_to_exu1_dec1_imm
                     : io_idu_to_exu1_dec1_val_rs2_val)
              : io_idu_to_exu1_dec1_op_is_sub
                  ? io_idu_to_exu1_dec1_val_rs1_val - io_idu_to_exu1_dec1_val_rs2_val
                  : io_idu_to_exu1_dec1_op_is_slti | io_idu_to_exu1_dec1_op_is_slt
                      ? {31'h0,
                         $signed(io_idu_to_exu1_dec1_val_rs1_val) < $signed(io_idu_to_exu1_dec1_op_is_slti
                                                                              ? io_idu_to_exu1_dec1_imm
                                                                              : io_idu_to_exu1_dec1_val_rs2_val)}
                      : io_idu_to_exu1_dec1_op_is_sltiu | io_idu_to_exu1_dec1_op_is_sltu
                          ? {31'h0,
                             io_idu_to_exu1_dec1_val_rs1_val < (io_idu_to_exu1_dec1_op_is_sltiu
                                                                  ? io_idu_to_exu1_dec1_imm
                                                                  : io_idu_to_exu1_dec1_val_rs2_val)}
                          : io_idu_to_exu1_dec1_op_is_xori | io_idu_to_exu1_dec1_op_is_xor
                              ? io_idu_to_exu1_dec1_val_rs1_val
                                ^ (io_idu_to_exu1_dec1_op_is_xori
                                     ? io_idu_to_exu1_dec1_imm
                                     : io_idu_to_exu1_dec1_val_rs2_val)
                              : io_idu_to_exu1_dec1_op_is_ori
                                | io_idu_to_exu1_dec1_op_is_or
                                  ? io_idu_to_exu1_dec1_val_rs1_val
                                    | (io_idu_to_exu1_dec1_op_is_ori
                                         ? io_idu_to_exu1_dec1_imm
                                         : io_idu_to_exu1_dec1_val_rs2_val)
                                  : io_idu_to_exu1_dec1_op_is_andi
                                    | io_idu_to_exu1_dec1_op_is_and
                                      ? io_idu_to_exu1_dec1_val_rs1_val
                                        & (io_idu_to_exu1_dec1_op_is_andi
                                             ? io_idu_to_exu1_dec1_imm
                                             : io_idu_to_exu1_dec1_val_rs2_val)
                                      : io_idu_to_exu1_dec1_op_is_slli
                                        | io_idu_to_exu1_dec1_op_is_sll
                                          ? aluOut_sll[31:0]
                                          : io_idu_to_exu1_dec1_op_is_srli
                                            | io_idu_to_exu1_dec1_op_is_srl
                                              ? io_idu_to_exu1_dec1_val_rs1_val >> _GEN
                                              : io_idu_to_exu1_dec1_op_is_srai
                                                | io_idu_to_exu1_dec1_op_is_sra
                                                  ? $signed($signed(io_idu_to_exu1_dec1_val_rs1_val)
                                                            >>> _GEN)
                                                  : is_jump
                                                      ? io_idu_to_exu1_dec1_val_nextpc
                                                      : 32'h0;
  wire        is_branch =
    io_idu_to_exu1_dec1_op_is_beq | io_idu_to_exu1_dec1_op_is_bne
    | io_idu_to_exu1_dec1_op_is_blt | io_idu_to_exu1_dec1_op_is_bge
    | io_idu_to_exu1_dec1_op_is_bltu | io_idu_to_exu1_dec1_op_is_bgeu;
  wire [31:0] _mem_addr_T = io_idu_to_exu1_dec1_val_rs1_val + io_idu_to_exu1_dec1_imm;
  wire        is_load =
    io_idu_to_exu1_dec1_op_is_lb | io_idu_to_exu1_dec1_op_is_lh
    | io_idu_to_exu1_dec1_op_is_lw | io_idu_to_exu1_dec1_op_is_lbu
    | io_idu_to_exu1_dec1_op_is_lhu;
  CSR csr (
    .clock                        (clock),
    .reset                        (reset),
    .io_exu_to_csr_addr           (io_idu_to_exu1_inst1[31:20]),
    .io_exu_to_csr_wen
      ((_is_csr_T | io_idu_to_exu1_dec1_op_is_csrrc | io_idu_to_exu1_dec1_op_is_csrrwi
        | io_idu_to_exu1_dec1_op_is_csrrsi | io_idu_to_exu1_dec1_op_is_csrrci)
       & (io_idu_to_exu1_dec1_op_is_csrrw | io_idu_to_exu1_dec1_op_is_csrrwi
          | (use_imm_csr
               ? (|(io_idu_to_exu1_inst1[19:15]))
               : (|(io_idu_to_exu1_inst1[19:15]))))),
    .io_exu_to_csr_waddr          (io_idu_to_exu1_inst1[31:20]),
    .io_exu_to_csr_op
      (io_idu_to_exu1_dec1_op_is_csrrs | io_idu_to_exu1_dec1_op_is_csrrsi
         ? 3'h1
         : {1'h0,
            io_idu_to_exu1_dec1_op_is_csrrc | io_idu_to_exu1_dec1_op_is_csrrci,
            1'h0}),
    .io_exu_to_csr_rs1_val        (io_idu_to_exu1_dec1_val_rs1_val),
    .io_exu_to_csr_use_imm        (use_imm_csr),
    .io_exu_to_csr_ecall          (io_idu_to_exu1_dec1_op_is_ecall),
    .io_exu_to_csr_is_ebreak      (io_idu_to_exu1_dec1_op_is_ebreak),
    .io_exu_to_csr_current_pc     (io_idu_to_exu1_inst1_pc),
    .io_exu_to_csr_inst_retire
      (io_idu_to_exu1_dec1_op_is_ebreak | io_idu_to_exu1_dec1_op_is_ecall
         ? 2'h0
         : io_idu_to_exu1_is_stall ? 2'h1 : 2'h2),
    .io_csr_to_exu_rdata          (io_csr_to_grf_wdata),
    .io_csr_to_exu_take_trap      (io_csr_to_ifu_take_trap),
    .io_csr_to_exu_trap_pc        (io_csr_to_ifu_trap_pc),
    .io_csr_to_exu_debug_mcycle   (io_debug_csr_mcycle),
    .io_csr_to_exu_debug_minstret (io_debug_csr_minstret),
    .io_csr_to_exu_debug_mstatus  (io_debug_csr_mstatus),
    .io_csr_to_exu_debug_mie      (io_debug_csr_mie),
    .io_csr_to_exu_debug_mtvec    (io_debug_csr_mtvec),
    .io_csr_to_exu_debug_mepc     (_csr_io_csr_to_exu_debug_mepc),
    .io_csr_to_exu_debug_mcause   (io_debug_csr_mcause),
    .io_csr_to_exu_debug_mtval    (io_debug_csr_mtval),
    .io_csr_to_exu_debug_mip      (io_debug_csr_mip)
  );
  assign io_exu_to_lsu_op_is_lb = io_idu_to_exu1_dec1_op_is_lb;
  assign io_exu_to_lsu_op_is_lh = io_idu_to_exu1_dec1_op_is_lh;
  assign io_exu_to_lsu_op_is_lw = io_idu_to_exu1_dec1_op_is_lw;
  assign io_exu_to_lsu_op_is_lbu = io_idu_to_exu1_dec1_op_is_lbu;
  assign io_exu_to_lsu_op_is_lhu = io_idu_to_exu1_dec1_op_is_lhu;
  assign io_exu_to_lsu_op_is_sb = io_idu_to_exu1_dec1_op_is_sb;
  assign io_exu_to_lsu_op_is_sh = io_idu_to_exu1_dec1_op_is_sh;
  assign io_exu_to_lsu_op_is_sw = io_idu_to_exu1_dec1_op_is_sw;
  assign io_exu_to_lsu_op_is_ebreak = io_idu_to_exu1_dec1_op_is_ebreak;
  assign io_exu_to_lsu_paddr_addr = _mem_addr_T;
  assign io_exu_to_lsu_data_store_data = io_idu_to_exu1_dec1_val_rs2_val;
  assign io_exu_to_lsu_exu_through_lsu_to_wbu_rd =
    (io_idu_to_exu1_dec1_op_is_lui | io_idu_to_exu1_dec1_op_is_auipc
     | io_idu_to_exu1_dec1_op_is_jal | io_idu_to_exu1_dec1_op_is_jalr
     | io_idu_to_exu1_dec1_op_is_addi | io_idu_to_exu1_dec1_op_is_slti
     | io_idu_to_exu1_dec1_op_is_sltiu | io_idu_to_exu1_dec1_op_is_xori
     | io_idu_to_exu1_dec1_op_is_ori | io_idu_to_exu1_dec1_op_is_andi
     | io_idu_to_exu1_dec1_op_is_slli | io_idu_to_exu1_dec1_op_is_srli
     | io_idu_to_exu1_dec1_op_is_srai | io_idu_to_exu1_dec1_op_is_add
     | io_idu_to_exu1_dec1_op_is_sub | io_idu_to_exu1_dec1_op_is_sll
     | io_idu_to_exu1_dec1_op_is_slt | io_idu_to_exu1_dec1_op_is_sltu
     | io_idu_to_exu1_dec1_op_is_xor | io_idu_to_exu1_dec1_op_is_srl
     | io_idu_to_exu1_dec1_op_is_sra | io_idu_to_exu1_dec1_op_is_or
     | io_idu_to_exu1_dec1_op_is_and) & ~io_idu_to_exu1_dec1_op_is_ebreak | is_load
      ? io_idu_to_exu1_dec1_rd
      : 5'h0;
  assign io_exu_to_lsu_exu_through_lsu_to_wbu_grf_wb_data = is_load ? 32'h0 : alu_out;
  assign io_exu_to_ifu_take_branch =
    is_jump | is_branch
    & (io_idu_to_exu1_dec1_op_is_beq
         ? io_idu_to_exu1_dec1_val_rs1_val == io_idu_to_exu1_dec1_val_rs2_val
         : io_idu_to_exu1_dec1_op_is_bne
             ? io_idu_to_exu1_dec1_val_rs1_val != io_idu_to_exu1_dec1_val_rs2_val
             : io_idu_to_exu1_dec1_op_is_blt
                 ? $signed(io_idu_to_exu1_dec1_val_rs1_val) < $signed(io_idu_to_exu1_dec1_val_rs2_val)
                 : io_idu_to_exu1_dec1_op_is_bge
                     ? $signed(io_idu_to_exu1_dec1_val_rs1_val) >= $signed(io_idu_to_exu1_dec1_val_rs2_val)
                     : io_idu_to_exu1_dec1_op_is_bltu
                         ? io_idu_to_exu1_dec1_val_rs1_val < io_idu_to_exu1_dec1_val_rs2_val
                         : io_idu_to_exu1_dec1_op_is_bgeu
                           & io_idu_to_exu1_dec1_val_rs1_val >= io_idu_to_exu1_dec1_val_rs2_val);
  assign io_exu_to_ifu_branch_target =
    io_idu_to_exu1_dec1_op_is_jal
      ? _target_branch_T
      : io_idu_to_exu1_dec1_op_is_jalr
          ? {_mem_addr_T[31:1], 1'h0}
          : is_branch ? _target_branch_T : 32'h0;
  assign io_csr_to_ifu_take_mret = io_idu_to_exu1_dec1_op_is_mret;
  assign io_csr_to_ifu_mret_pc = _csr_io_csr_to_exu_debug_mepc;
  assign io_csr_to_grf_wen =
    (_is_csr_T | io_idu_to_exu1_dec1_op_is_csrrc | io_idu_to_exu1_dec1_op_is_csrrwi
     | io_idu_to_exu1_dec1_op_is_csrrsi | io_idu_to_exu1_dec1_op_is_csrrci)
    & (|(io_idu_to_exu1_inst1[11:7]));
  assign io_csr_to_grf_waddr = io_idu_to_exu1_inst1[11:7];
  assign io_debug_csr_mepc = _csr_io_csr_to_exu_debug_mepc;
  assign io_debug_alu_out = alu_out;
  assign io_debug_alu_source1 =
    io_idu_to_exu1_dec1_op_is_auipc | io_idu_to_exu1_dec1_op_is_jal
      ? _pc_T
      : io_idu_to_exu1_dec1_op_is_lui ? 32'h0 : io_idu_to_exu1_dec1_val_rs1_val;
  assign io_debug_alu_source2 =
    io_idu_to_exu1_dec1_op_is_addi | io_idu_to_exu1_dec1_op_is_slti
    | io_idu_to_exu1_dec1_op_is_sltiu | io_idu_to_exu1_dec1_op_is_xori
    | io_idu_to_exu1_dec1_op_is_ori | io_idu_to_exu1_dec1_op_is_andi
    | io_idu_to_exu1_dec1_op_is_slli | io_idu_to_exu1_dec1_op_is_srli
    | io_idu_to_exu1_dec1_op_is_srai | io_idu_to_exu1_dec1_op_is_jalr
    | io_idu_to_exu1_dec1_op_is_lb | io_idu_to_exu1_dec1_op_is_lh
    | io_idu_to_exu1_dec1_op_is_lw | io_idu_to_exu1_dec1_op_is_lbu
    | io_idu_to_exu1_dec1_op_is_lhu | io_idu_to_exu1_dec1_op_is_sb
    | io_idu_to_exu1_dec1_op_is_sh | io_idu_to_exu1_dec1_op_is_sw
      ? io_idu_to_exu1_dec1_imm
      : io_idu_to_exu1_dec1_val_rs2_val;
  assign io_debug_agu_out = _mem_addr_T;
endmodule

