// Generated by CIRCT firtool-1.139.0
module GRF(
  input         clock,
                reset,
                io_rs1en,
  input  [4:0]  io_rs1addr,
  output [31:0] io_rs1out,
  input         io_rs2en,
  input  [4:0]  io_rs2addr,
  output [31:0] io_rs2out,
  input         io_rden,
  input  [4:0]  io_rdaddr,
  input  [31:0] io_input,
  output [31:0] io_debug_regs_0,
                io_debug_regs_1,
                io_debug_regs_2,
                io_debug_regs_3,
                io_debug_regs_4,
                io_debug_regs_5,
                io_debug_regs_6,
                io_debug_regs_7,
                io_debug_regs_8,
                io_debug_regs_9,
                io_debug_regs_10,
                io_debug_regs_11,
                io_debug_regs_12,
                io_debug_regs_13,
                io_debug_regs_14,
                io_debug_regs_15,
  output        io_debug_rden,
  output [4:0]  io_debug_rdaddr,
  output [31:0] io_debug_input
);

  reg  [31:0]       regs_0;
  reg  [31:0]       regs_1;
  reg  [31:0]       regs_2;
  reg  [31:0]       regs_3;
  reg  [31:0]       regs_4;
  reg  [31:0]       regs_5;
  reg  [31:0]       regs_6;
  reg  [31:0]       regs_7;
  reg  [31:0]       regs_8;
  reg  [31:0]       regs_9;
  reg  [31:0]       regs_10;
  reg  [31:0]       regs_11;
  reg  [31:0]       regs_12;
  reg  [31:0]       regs_13;
  reg  [31:0]       regs_14;
  reg  [31:0]       regs_15;
  wire [15:0][31:0] _GEN =
    {{regs_15},
     {regs_14},
     {regs_13},
     {regs_12},
     {regs_11},
     {regs_10},
     {regs_9},
     {regs_8},
     {regs_7},
     {regs_6},
     {regs_5},
     {regs_4},
     {regs_3},
     {regs_2},
     {regs_1},
     {regs_0}};
  always @(posedge clock) begin
    if (reset) begin
      regs_0 <= 32'h0;
      regs_1 <= 32'h0;
      regs_2 <= 32'h0;
      regs_3 <= 32'h0;
      regs_4 <= 32'h0;
      regs_5 <= 32'h0;
      regs_6 <= 32'h0;
      regs_7 <= 32'h0;
      regs_8 <= 32'h0;
      regs_9 <= 32'h0;
      regs_10 <= 32'h0;
      regs_11 <= 32'h0;
      regs_12 <= 32'h0;
      regs_13 <= 32'h0;
      regs_14 <= 32'h0;
      regs_15 <= 32'h0;
    end
    else begin
      automatic logic        _regs_T_4;
      automatic logic [31:0] _GEN_0;
      _regs_T_4 = io_rden & ~(io_rdaddr[4]) & (|io_rdaddr);
      _GEN_0 = _GEN[io_rdaddr[3:0]];
      if (io_rdaddr[3:0] == 4'h0) begin
        if (_regs_T_4)
          regs_0 <= io_input;
        else
          regs_0 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'h1) begin
        if (_regs_T_4)
          regs_1 <= io_input;
        else
          regs_1 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'h2) begin
        if (_regs_T_4)
          regs_2 <= io_input;
        else
          regs_2 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'h3) begin
        if (_regs_T_4)
          regs_3 <= io_input;
        else
          regs_3 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'h4) begin
        if (_regs_T_4)
          regs_4 <= io_input;
        else
          regs_4 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'h5) begin
        if (_regs_T_4)
          regs_5 <= io_input;
        else
          regs_5 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'h6) begin
        if (_regs_T_4)
          regs_6 <= io_input;
        else
          regs_6 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'h7) begin
        if (_regs_T_4)
          regs_7 <= io_input;
        else
          regs_7 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'h8) begin
        if (_regs_T_4)
          regs_8 <= io_input;
        else
          regs_8 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'h9) begin
        if (_regs_T_4)
          regs_9 <= io_input;
        else
          regs_9 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'hA) begin
        if (_regs_T_4)
          regs_10 <= io_input;
        else
          regs_10 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'hB) begin
        if (_regs_T_4)
          regs_11 <= io_input;
        else
          regs_11 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'hC) begin
        if (_regs_T_4)
          regs_12 <= io_input;
        else
          regs_12 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'hD) begin
        if (_regs_T_4)
          regs_13 <= io_input;
        else
          regs_13 <= _GEN_0;
      end
      if (io_rdaddr[3:0] == 4'hE) begin
        if (_regs_T_4)
          regs_14 <= io_input;
        else
          regs_14 <= _GEN_0;
      end
      if (&(io_rdaddr[3:0])) begin
        if (_regs_T_4)
          regs_15 <= io_input;
        else
          regs_15 <= _GEN_0;
      end
    end
  end // always @(posedge)
  assign io_rs1out =
    io_rs1en & ~(io_rs1addr[4]) & (|io_rs1addr) ? _GEN[io_rs1addr[3:0]] : 32'h0;
  assign io_rs2out =
    io_rs2en & ~(io_rs2addr[4]) & (|io_rs2addr) ? _GEN[io_rs2addr[3:0]] : 32'h0;
  assign io_debug_regs_0 = regs_0;
  assign io_debug_regs_1 = regs_1;
  assign io_debug_regs_2 = regs_2;
  assign io_debug_regs_3 = regs_3;
  assign io_debug_regs_4 = regs_4;
  assign io_debug_regs_5 = regs_5;
  assign io_debug_regs_6 = regs_6;
  assign io_debug_regs_7 = regs_7;
  assign io_debug_regs_8 = regs_8;
  assign io_debug_regs_9 = regs_9;
  assign io_debug_regs_10 = regs_10;
  assign io_debug_regs_11 = regs_11;
  assign io_debug_regs_12 = regs_12;
  assign io_debug_regs_13 = regs_13;
  assign io_debug_regs_14 = regs_14;
  assign io_debug_regs_15 = regs_15;
  assign io_debug_rden = io_rden;
  assign io_debug_rdaddr = io_rdaddr;
  assign io_debug_input = io_input;
endmodule

