// Generated by CIRCT firtool-1.139.0
module GRF(
  input         clock,
                reset,
  input  [4:0]  io_idu_to_grf_dec1_redreg_rs1,
                io_idu_to_grf_dec1_redreg_rs2,
                io_idu_to_grf_dec2_redreg_rs1,
                io_idu_to_grf_dec2_redreg_rs2,
  output [31:0] io_grf_to_idu_dec1_value_inst1rs1_value,
                io_grf_to_idu_dec1_value_inst1rs2_value,
                io_grf_to_idu_dec2_value_inst2rs1_value,
                io_grf_to_idu_dec2_value_inst2rs2_value,
  input  [4:0]  io_wbu_to_grf_wr1_addr,
  input  [31:0] io_wbu_to_grf_wr1_data,
  input  [4:0]  io_wbu_to_grf_wr2_addr,
  input  [31:0] io_wbu_to_grf_wr2_data,
  input         io_csr_to_grf_wen,
  input  [4:0]  io_csr_to_grf_waddr,
  input  [31:0] io_csr_to_grf_wdata,
  output [31:0] io_debug_regs_0,
                io_debug_regs_1,
                io_debug_regs_2,
                io_debug_regs_3,
                io_debug_regs_4,
                io_debug_regs_5,
                io_debug_regs_6,
                io_debug_regs_7,
                io_debug_regs_8,
                io_debug_regs_9,
                io_debug_regs_10,
                io_debug_regs_11,
                io_debug_regs_12,
                io_debug_regs_13,
                io_debug_regs_14,
                io_debug_regs_15,
  output        io_debug_rden,
  output [4:0]  io_debug_rdaddr,
  output [31:0] io_debug_input
);

  reg  [31:0]       regs_0;
  reg  [31:0]       regs_1;
  reg  [31:0]       regs_2;
  reg  [31:0]       regs_3;
  reg  [31:0]       regs_4;
  reg  [31:0]       regs_5;
  reg  [31:0]       regs_6;
  reg  [31:0]       regs_7;
  reg  [31:0]       regs_8;
  reg  [31:0]       regs_9;
  reg  [31:0]       regs_10;
  reg  [31:0]       regs_11;
  reg  [31:0]       regs_12;
  reg  [31:0]       regs_13;
  reg  [31:0]       regs_14;
  reg  [31:0]       regs_15;
  wire [15:0][31:0] _GEN =
    {{regs_15},
     {regs_14},
     {regs_13},
     {regs_12},
     {regs_11},
     {regs_10},
     {regs_9},
     {regs_8},
     {regs_7},
     {regs_6},
     {regs_5},
     {regs_4},
     {regs_3},
     {regs_2},
     {regs_1},
     {regs_0}};
  always @(posedge clock) begin
    if (reset) begin
      regs_0 <= 32'h0;
      regs_1 <= 32'h0;
      regs_2 <= 32'h0;
      regs_3 <= 32'h0;
      regs_4 <= 32'h0;
      regs_5 <= 32'h0;
      regs_6 <= 32'h0;
      regs_7 <= 32'h0;
      regs_8 <= 32'h0;
      regs_9 <= 32'h0;
      regs_10 <= 32'h0;
      regs_11 <= 32'h0;
      regs_12 <= 32'h0;
      regs_13 <= 32'h0;
      regs_14 <= 32'h0;
      regs_15 <= 32'h0;
    end
    else begin
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'h0 & io_csr_to_grf_wen)
        regs_0 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'h0)
        regs_0 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'h0)
        regs_0 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'h1 & io_csr_to_grf_wen)
        regs_1 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'h1)
        regs_1 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'h1)
        regs_1 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'h2 & io_csr_to_grf_wen)
        regs_2 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'h2)
        regs_2 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'h2)
        regs_2 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'h3 & io_csr_to_grf_wen)
        regs_3 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'h3)
        regs_3 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'h3)
        regs_3 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'h4 & io_csr_to_grf_wen)
        regs_4 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'h4)
        regs_4 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'h4)
        regs_4 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'h5 & io_csr_to_grf_wen)
        regs_5 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'h5)
        regs_5 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'h5)
        regs_5 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'h6 & io_csr_to_grf_wen)
        regs_6 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'h6)
        regs_6 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'h6)
        regs_6 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'h7 & io_csr_to_grf_wen)
        regs_7 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'h7)
        regs_7 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'h7)
        regs_7 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'h8 & io_csr_to_grf_wen)
        regs_8 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'h8)
        regs_8 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'h8)
        regs_8 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'h9 & io_csr_to_grf_wen)
        regs_9 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'h9)
        regs_9 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'h9)
        regs_9 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'hA & io_csr_to_grf_wen)
        regs_10 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'hA)
        regs_10 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'hA)
        regs_10 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'hB & io_csr_to_grf_wen)
        regs_11 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'hB)
        regs_11 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'hB)
        regs_11 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'hC & io_csr_to_grf_wen)
        regs_12 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'hC)
        regs_12 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'hC)
        regs_12 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'hD & io_csr_to_grf_wen)
        regs_13 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'hD)
        regs_13 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'hD)
        regs_13 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & io_csr_to_grf_waddr[3:0] == 4'hE & io_csr_to_grf_wen)
        regs_14 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & io_wbu_to_grf_wr1_addr[3:0] == 4'hE)
        regs_14 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & io_wbu_to_grf_wr2_addr[3:0] == 4'hE)
        regs_14 <= io_wbu_to_grf_wr2_data;
      if ((|io_csr_to_grf_waddr) & ~(io_csr_to_grf_waddr[4])
          & (&(io_csr_to_grf_waddr[3:0])) & io_csr_to_grf_wen)
        regs_15 <= io_csr_to_grf_wdata;
      else if ((|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4])
               & (&(io_wbu_to_grf_wr1_addr[3:0])))
        regs_15 <= io_wbu_to_grf_wr1_data;
      else if ((|io_wbu_to_grf_wr2_addr) & ~(io_wbu_to_grf_wr2_addr[4])
               & (&(io_wbu_to_grf_wr2_addr[3:0])))
        regs_15 <= io_wbu_to_grf_wr2_data;
    end
  end // always @(posedge)
  assign io_grf_to_idu_dec1_value_inst1rs1_value =
    (|io_idu_to_grf_dec1_redreg_rs1) & ~(io_idu_to_grf_dec1_redreg_rs1[4])
      ? _GEN[io_idu_to_grf_dec1_redreg_rs1[3:0]]
      : 32'h0;
  assign io_grf_to_idu_dec1_value_inst1rs2_value =
    (|io_idu_to_grf_dec1_redreg_rs2) & ~(io_idu_to_grf_dec1_redreg_rs2[4])
      ? _GEN[io_idu_to_grf_dec1_redreg_rs2[3:0]]
      : 32'h0;
  assign io_grf_to_idu_dec2_value_inst2rs1_value =
    (|io_idu_to_grf_dec2_redreg_rs1) & ~(io_idu_to_grf_dec2_redreg_rs1[4])
      ? _GEN[io_idu_to_grf_dec2_redreg_rs1[3:0]]
      : 32'h0;
  assign io_grf_to_idu_dec2_value_inst2rs2_value =
    (|io_idu_to_grf_dec2_redreg_rs2) & ~(io_idu_to_grf_dec2_redreg_rs2[4])
      ? _GEN[io_idu_to_grf_dec2_redreg_rs2[3:0]]
      : 32'h0;
  assign io_debug_regs_0 = regs_0;
  assign io_debug_regs_1 = regs_1;
  assign io_debug_regs_2 = regs_2;
  assign io_debug_regs_3 = regs_3;
  assign io_debug_regs_4 = regs_4;
  assign io_debug_regs_5 = regs_5;
  assign io_debug_regs_6 = regs_6;
  assign io_debug_regs_7 = regs_7;
  assign io_debug_regs_8 = regs_8;
  assign io_debug_regs_9 = regs_9;
  assign io_debug_regs_10 = regs_10;
  assign io_debug_regs_11 = regs_11;
  assign io_debug_regs_12 = regs_12;
  assign io_debug_regs_13 = regs_13;
  assign io_debug_regs_14 = regs_14;
  assign io_debug_regs_15 = regs_15;
  assign io_debug_rden = (|io_wbu_to_grf_wr1_addr) & ~(io_wbu_to_grf_wr1_addr[4]);
  assign io_debug_rdaddr = io_wbu_to_grf_wr1_addr;
  assign io_debug_input = io_wbu_to_grf_wr1_data;
endmodule

