// Generated by CIRCT firtool-1.139.0
module idu(
  input  [31:0] io_inst,
  output        io_is_addi,
                io_is_add,
                io_is_jalr,
                io_is_lui,
                io_is_lbu,
                io_is_lw,
                io_is_sb,
                io_is_sw,
                io_is_ebreak,
  output [4:0]  io_rd,
                io_rs1,
                io_rs2,
  output [31:0] io_imm20,
                io_imm12
);

  wire _instDecoder_io_is_addi;
  wire _instDecoder_io_is_add;
  wire _instDecoder_io_is_jalr;
  wire _instDecoder_io_is_lui;
  wire _instDecoder_io_is_lbu;
  wire _instDecoder_io_is_lw;
  wire _instDecoder_io_is_sb;
  wire _instDecoder_io_is_sw;
  InstructionDecoder instDecoder (
    .io_inst      (io_inst),
    .io_is_addi   (_instDecoder_io_is_addi),
    .io_is_add    (_instDecoder_io_is_add),
    .io_is_jalr   (_instDecoder_io_is_jalr),
    .io_is_lui    (_instDecoder_io_is_lui),
    .io_is_lbu    (_instDecoder_io_is_lbu),
    .io_is_lw     (_instDecoder_io_is_lw),
    .io_is_sb     (_instDecoder_io_is_sb),
    .io_is_sw     (_instDecoder_io_is_sw),
    .io_is_ebreak (io_is_ebreak)
  );
  InformationDecoder infoDecoder (
    .io_addi  (_instDecoder_io_is_addi),
    .io_add   (_instDecoder_io_is_add),
    .io_lui   (_instDecoder_io_is_lui),
    .io_jalr  (_instDecoder_io_is_jalr),
    .io_lbu   (_instDecoder_io_is_lbu),
    .io_lw    (_instDecoder_io_is_lw),
    .io_sw    (_instDecoder_io_is_sw),
    .io_sb    (_instDecoder_io_is_sb),
    .io_inst  (io_inst),
    .io_rd    (io_rd),
    .io_rs1   (io_rs1),
    .io_rs2   (io_rs2),
    .io_imm20 (io_imm20),
    .io_imm12 (io_imm12)
  );
  assign io_is_addi = _instDecoder_io_is_addi;
  assign io_is_add = _instDecoder_io_is_add;
  assign io_is_jalr = _instDecoder_io_is_jalr;
  assign io_is_lui = _instDecoder_io_is_lui;
  assign io_is_lbu = _instDecoder_io_is_lbu;
  assign io_is_lw = _instDecoder_io_is_lw;
  assign io_is_sb = _instDecoder_io_is_sb;
  assign io_is_sw = _instDecoder_io_is_sw;
endmodule

