// Generated by CIRCT firtool-1.139.0
module idu(
  input  [31:0] io_inst,
  output        io_is_lui,
                io_is_auipc,
                io_is_jal,
                io_is_jalr,
                io_is_beq,
                io_is_bne,
                io_is_blt,
                io_is_bge,
                io_is_bltu,
                io_is_bgeu,
                io_is_lb,
                io_is_lh,
                io_is_lw,
                io_is_lbu,
                io_is_lhu,
                io_is_sb,
                io_is_sh,
                io_is_sw,
                io_is_addi,
                io_is_slti,
                io_is_sltiu,
                io_is_xori,
                io_is_ori,
                io_is_andi,
                io_is_slli,
                io_is_srli,
                io_is_srai,
                io_is_add,
                io_is_sub,
                io_is_sll,
                io_is_slt,
                io_is_sltu,
                io_is_xor,
                io_is_srl,
                io_is_sra,
                io_is_or,
                io_is_and,
                io_is_ebreak,
  output [4:0]  io_rd,
                io_rs1,
                io_rs2,
  output [31:0] io_imm_i,
                io_imm_s,
                io_imm_b,
                io_imm_u,
                io_imm_j,
                io_debug_inst
);

  wire _instDecoder_io_is_lui;
  wire _instDecoder_io_is_auipc;
  wire _instDecoder_io_is_jal;
  wire _instDecoder_io_is_jalr;
  wire _instDecoder_io_is_beq;
  wire _instDecoder_io_is_bne;
  wire _instDecoder_io_is_blt;
  wire _instDecoder_io_is_bge;
  wire _instDecoder_io_is_bltu;
  wire _instDecoder_io_is_bgeu;
  wire _instDecoder_io_is_lb;
  wire _instDecoder_io_is_lh;
  wire _instDecoder_io_is_lw;
  wire _instDecoder_io_is_lbu;
  wire _instDecoder_io_is_lhu;
  wire _instDecoder_io_is_sb;
  wire _instDecoder_io_is_sh;
  wire _instDecoder_io_is_sw;
  wire _instDecoder_io_is_addi;
  wire _instDecoder_io_is_slti;
  wire _instDecoder_io_is_sltiu;
  wire _instDecoder_io_is_xori;
  wire _instDecoder_io_is_ori;
  wire _instDecoder_io_is_andi;
  wire _instDecoder_io_is_slli;
  wire _instDecoder_io_is_srli;
  wire _instDecoder_io_is_srai;
  wire _instDecoder_io_is_add;
  wire _instDecoder_io_is_sub;
  wire _instDecoder_io_is_sll;
  wire _instDecoder_io_is_slt;
  wire _instDecoder_io_is_sltu;
  wire _instDecoder_io_is_xor;
  wire _instDecoder_io_is_srl;
  wire _instDecoder_io_is_sra;
  wire _instDecoder_io_is_or;
  wire _instDecoder_io_is_and;
  InstructionDecoder instDecoder (
    .io_inst      (io_inst),
    .io_is_lui    (_instDecoder_io_is_lui),
    .io_is_auipc  (_instDecoder_io_is_auipc),
    .io_is_jal    (_instDecoder_io_is_jal),
    .io_is_jalr   (_instDecoder_io_is_jalr),
    .io_is_beq    (_instDecoder_io_is_beq),
    .io_is_bne    (_instDecoder_io_is_bne),
    .io_is_blt    (_instDecoder_io_is_blt),
    .io_is_bge    (_instDecoder_io_is_bge),
    .io_is_bltu   (_instDecoder_io_is_bltu),
    .io_is_bgeu   (_instDecoder_io_is_bgeu),
    .io_is_lb     (_instDecoder_io_is_lb),
    .io_is_lh     (_instDecoder_io_is_lh),
    .io_is_lw     (_instDecoder_io_is_lw),
    .io_is_lbu    (_instDecoder_io_is_lbu),
    .io_is_lhu    (_instDecoder_io_is_lhu),
    .io_is_sb     (_instDecoder_io_is_sb),
    .io_is_sh     (_instDecoder_io_is_sh),
    .io_is_sw     (_instDecoder_io_is_sw),
    .io_is_addi   (_instDecoder_io_is_addi),
    .io_is_slti   (_instDecoder_io_is_slti),
    .io_is_sltiu  (_instDecoder_io_is_sltiu),
    .io_is_xori   (_instDecoder_io_is_xori),
    .io_is_ori    (_instDecoder_io_is_ori),
    .io_is_andi   (_instDecoder_io_is_andi),
    .io_is_slli   (_instDecoder_io_is_slli),
    .io_is_srli   (_instDecoder_io_is_srli),
    .io_is_srai   (_instDecoder_io_is_srai),
    .io_is_add    (_instDecoder_io_is_add),
    .io_is_sub    (_instDecoder_io_is_sub),
    .io_is_sll    (_instDecoder_io_is_sll),
    .io_is_slt    (_instDecoder_io_is_slt),
    .io_is_sltu   (_instDecoder_io_is_sltu),
    .io_is_xor    (_instDecoder_io_is_xor),
    .io_is_srl    (_instDecoder_io_is_srl),
    .io_is_sra    (_instDecoder_io_is_sra),
    .io_is_or     (_instDecoder_io_is_or),
    .io_is_and    (_instDecoder_io_is_and),
    .io_is_ebreak (io_is_ebreak)
  );
  InformationDecoder infoDecoder (
    .io_is_lui   (_instDecoder_io_is_lui),
    .io_is_auipc (_instDecoder_io_is_auipc),
    .io_is_jal   (_instDecoder_io_is_jal),
    .io_is_jalr  (_instDecoder_io_is_jalr),
    .io_is_beq   (_instDecoder_io_is_beq),
    .io_is_bne   (_instDecoder_io_is_bne),
    .io_is_blt   (_instDecoder_io_is_blt),
    .io_is_bge   (_instDecoder_io_is_bge),
    .io_is_bltu  (_instDecoder_io_is_bltu),
    .io_is_bgeu  (_instDecoder_io_is_bgeu),
    .io_is_lb    (_instDecoder_io_is_lb),
    .io_is_lh    (_instDecoder_io_is_lh),
    .io_is_lw    (_instDecoder_io_is_lw),
    .io_is_lbu   (_instDecoder_io_is_lbu),
    .io_is_lhu   (_instDecoder_io_is_lhu),
    .io_is_sb    (_instDecoder_io_is_sb),
    .io_is_sh    (_instDecoder_io_is_sh),
    .io_is_sw    (_instDecoder_io_is_sw),
    .io_is_addi  (_instDecoder_io_is_addi),
    .io_is_slti  (_instDecoder_io_is_slti),
    .io_is_sltiu (_instDecoder_io_is_sltiu),
    .io_is_xori  (_instDecoder_io_is_xori),
    .io_is_ori   (_instDecoder_io_is_ori),
    .io_is_andi  (_instDecoder_io_is_andi),
    .io_is_slli  (_instDecoder_io_is_slli),
    .io_is_srli  (_instDecoder_io_is_srli),
    .io_is_srai  (_instDecoder_io_is_srai),
    .io_is_add   (_instDecoder_io_is_add),
    .io_is_sub   (_instDecoder_io_is_sub),
    .io_is_sll   (_instDecoder_io_is_sll),
    .io_is_slt   (_instDecoder_io_is_slt),
    .io_is_sltu  (_instDecoder_io_is_sltu),
    .io_is_xor   (_instDecoder_io_is_xor),
    .io_is_srl   (_instDecoder_io_is_srl),
    .io_is_sra   (_instDecoder_io_is_sra),
    .io_is_or    (_instDecoder_io_is_or),
    .io_is_and   (_instDecoder_io_is_and),
    .io_inst     (io_inst),
    .io_rd       (io_rd),
    .io_rs1      (io_rs1),
    .io_rs2      (io_rs2),
    .io_imm_i    (io_imm_i),
    .io_imm_s    (io_imm_s),
    .io_imm_b    (io_imm_b),
    .io_imm_u    (io_imm_u),
    .io_imm_j    (io_imm_j)
  );
  assign io_is_lui = _instDecoder_io_is_lui;
  assign io_is_auipc = _instDecoder_io_is_auipc;
  assign io_is_jal = _instDecoder_io_is_jal;
  assign io_is_jalr = _instDecoder_io_is_jalr;
  assign io_is_beq = _instDecoder_io_is_beq;
  assign io_is_bne = _instDecoder_io_is_bne;
  assign io_is_blt = _instDecoder_io_is_blt;
  assign io_is_bge = _instDecoder_io_is_bge;
  assign io_is_bltu = _instDecoder_io_is_bltu;
  assign io_is_bgeu = _instDecoder_io_is_bgeu;
  assign io_is_lb = _instDecoder_io_is_lb;
  assign io_is_lh = _instDecoder_io_is_lh;
  assign io_is_lw = _instDecoder_io_is_lw;
  assign io_is_lbu = _instDecoder_io_is_lbu;
  assign io_is_lhu = _instDecoder_io_is_lhu;
  assign io_is_sb = _instDecoder_io_is_sb;
  assign io_is_sh = _instDecoder_io_is_sh;
  assign io_is_sw = _instDecoder_io_is_sw;
  assign io_is_addi = _instDecoder_io_is_addi;
  assign io_is_slti = _instDecoder_io_is_slti;
  assign io_is_sltiu = _instDecoder_io_is_sltiu;
  assign io_is_xori = _instDecoder_io_is_xori;
  assign io_is_ori = _instDecoder_io_is_ori;
  assign io_is_andi = _instDecoder_io_is_andi;
  assign io_is_slli = _instDecoder_io_is_slli;
  assign io_is_srli = _instDecoder_io_is_srli;
  assign io_is_srai = _instDecoder_io_is_srai;
  assign io_is_add = _instDecoder_io_is_add;
  assign io_is_sub = _instDecoder_io_is_sub;
  assign io_is_sll = _instDecoder_io_is_sll;
  assign io_is_slt = _instDecoder_io_is_slt;
  assign io_is_sltu = _instDecoder_io_is_sltu;
  assign io_is_xor = _instDecoder_io_is_xor;
  assign io_is_srl = _instDecoder_io_is_srl;
  assign io_is_sra = _instDecoder_io_is_sra;
  assign io_is_or = _instDecoder_io_is_or;
  assign io_is_and = _instDecoder_io_is_and;
  assign io_debug_inst = io_inst;
endmodule

