// Generated by CIRCT firtool-1.139.0
module idu(
  input  [31:0] io_ifu_to_idu_inst1,
                io_ifu_to_idu_inst2,
                io_ifu_to_idu_inst1_pc,
                io_ifu_to_idu_inst1_nextpc,
                io_ifu_to_idu_inst2_nextpc,
                io_grf_to_idu_dec1_value_inst1rs1_value,
                io_grf_to_idu_dec1_value_inst1rs2_value,
                io_grf_to_idu_dec2_value_inst2rs1_value,
                io_grf_to_idu_dec2_value_inst2rs2_value,
  output [4:0]  io_idu_to_grf_dec1_redreg_rs1,
                io_idu_to_grf_dec1_redreg_rs2,
                io_idu_to_grf_dec2_redreg_rs1,
                io_idu_to_grf_dec2_redreg_rs2,
  output        io_idu_to_exu1_dec1_op_is_lui,
                io_idu_to_exu1_dec1_op_is_auipc,
                io_idu_to_exu1_dec1_op_is_jal,
                io_idu_to_exu1_dec1_op_is_jalr,
                io_idu_to_exu1_dec1_op_is_beq,
                io_idu_to_exu1_dec1_op_is_bne,
                io_idu_to_exu1_dec1_op_is_blt,
                io_idu_to_exu1_dec1_op_is_bge,
                io_idu_to_exu1_dec1_op_is_bltu,
                io_idu_to_exu1_dec1_op_is_bgeu,
                io_idu_to_exu1_dec1_op_is_lb,
                io_idu_to_exu1_dec1_op_is_lh,
                io_idu_to_exu1_dec1_op_is_lw,
                io_idu_to_exu1_dec1_op_is_lbu,
                io_idu_to_exu1_dec1_op_is_lhu,
                io_idu_to_exu1_dec1_op_is_sb,
                io_idu_to_exu1_dec1_op_is_sh,
                io_idu_to_exu1_dec1_op_is_sw,
                io_idu_to_exu1_dec1_op_is_addi,
                io_idu_to_exu1_dec1_op_is_slti,
                io_idu_to_exu1_dec1_op_is_sltiu,
                io_idu_to_exu1_dec1_op_is_xori,
                io_idu_to_exu1_dec1_op_is_ori,
                io_idu_to_exu1_dec1_op_is_andi,
                io_idu_to_exu1_dec1_op_is_slli,
                io_idu_to_exu1_dec1_op_is_srli,
                io_idu_to_exu1_dec1_op_is_srai,
                io_idu_to_exu1_dec1_op_is_add,
                io_idu_to_exu1_dec1_op_is_sub,
                io_idu_to_exu1_dec1_op_is_sll,
                io_idu_to_exu1_dec1_op_is_slt,
                io_idu_to_exu1_dec1_op_is_sltu,
                io_idu_to_exu1_dec1_op_is_xor,
                io_idu_to_exu1_dec1_op_is_srl,
                io_idu_to_exu1_dec1_op_is_sra,
                io_idu_to_exu1_dec1_op_is_or,
                io_idu_to_exu1_dec1_op_is_and,
                io_idu_to_exu1_dec1_op_is_ebreak,
  output [31:0] io_idu_to_exu1_dec1_imm,
                io_idu_to_exu1_dec1_val_rs1_val,
                io_idu_to_exu1_dec1_val_rs2_val,
                io_idu_to_exu1_dec1_val_nextpc,
  output [4:0]  io_idu_to_exu1_dec1_rd,
  output        io_idu_to_exu2_dec2_op_is_lui,
                io_idu_to_exu2_dec2_op_is_auipc,
                io_idu_to_exu2_dec2_op_is_jal,
                io_idu_to_exu2_dec2_op_is_jalr,
                io_idu_to_exu2_dec2_op_is_beq,
                io_idu_to_exu2_dec2_op_is_bne,
                io_idu_to_exu2_dec2_op_is_blt,
                io_idu_to_exu2_dec2_op_is_bge,
                io_idu_to_exu2_dec2_op_is_bltu,
                io_idu_to_exu2_dec2_op_is_bgeu,
                io_idu_to_exu2_dec2_op_is_lb,
                io_idu_to_exu2_dec2_op_is_lh,
                io_idu_to_exu2_dec2_op_is_lw,
                io_idu_to_exu2_dec2_op_is_lbu,
                io_idu_to_exu2_dec2_op_is_lhu,
                io_idu_to_exu2_dec2_op_is_sb,
                io_idu_to_exu2_dec2_op_is_sh,
                io_idu_to_exu2_dec2_op_is_sw,
                io_idu_to_exu2_dec2_op_is_addi,
                io_idu_to_exu2_dec2_op_is_slti,
                io_idu_to_exu2_dec2_op_is_sltiu,
                io_idu_to_exu2_dec2_op_is_xori,
                io_idu_to_exu2_dec2_op_is_ori,
                io_idu_to_exu2_dec2_op_is_andi,
                io_idu_to_exu2_dec2_op_is_slli,
                io_idu_to_exu2_dec2_op_is_srli,
                io_idu_to_exu2_dec2_op_is_srai,
                io_idu_to_exu2_dec2_op_is_add,
                io_idu_to_exu2_dec2_op_is_sub,
                io_idu_to_exu2_dec2_op_is_sll,
                io_idu_to_exu2_dec2_op_is_slt,
                io_idu_to_exu2_dec2_op_is_sltu,
                io_idu_to_exu2_dec2_op_is_xor,
                io_idu_to_exu2_dec2_op_is_srl,
                io_idu_to_exu2_dec2_op_is_sra,
                io_idu_to_exu2_dec2_op_is_or,
                io_idu_to_exu2_dec2_op_is_and,
                io_idu_to_exu2_dec2_op_is_ebreak,
  output [31:0] io_idu_to_exu2_dec2_imm,
                io_idu_to_exu2_dec2_val_rs1_val,
                io_idu_to_exu2_dec2_val_rs2_val,
                io_idu_to_exu2_dec2_val_nextpc,
  output [4:0]  io_idu_to_exu2_dec2_rd,
  output        io_idu_to_ifu_is_stall,
                io_idu_to_top_is_csrrw,
                io_idu_to_top_is_csrrs,
                io_idu_to_top_is_csrrc,
                io_idu_to_top_is_csrrwi,
                io_idu_to_top_is_csrrsi,
                io_idu_to_top_is_csrrci,
                io_idu_to_top_is_ecall,
                io_idu_to_top_is_mret,
                io_idu_to_top_is_ebreak,
  output [31:0] io_idu_to_top_inst1_pc,
                io_idu_to_top_inst1,
                io_idu_to_top_rs1_val,
                io_idu_debug_debug_inst1,
                io_idu_debug_debug_inst2,
  output        io_idu_debug_is_stall
);

  wire        _dec2_io_is_lui;
  wire        _dec2_io_is_auipc;
  wire        _dec2_io_is_jal;
  wire        _dec2_io_is_jalr;
  wire        _dec2_io_is_beq;
  wire        _dec2_io_is_bne;
  wire        _dec2_io_is_blt;
  wire        _dec2_io_is_bge;
  wire        _dec2_io_is_bltu;
  wire        _dec2_io_is_bgeu;
  wire        _dec2_io_is_lb;
  wire        _dec2_io_is_lh;
  wire        _dec2_io_is_lw;
  wire        _dec2_io_is_lbu;
  wire        _dec2_io_is_lhu;
  wire        _dec2_io_is_sb;
  wire        _dec2_io_is_sh;
  wire        _dec2_io_is_sw;
  wire        _dec2_io_is_addi;
  wire        _dec2_io_is_slti;
  wire        _dec2_io_is_sltiu;
  wire        _dec2_io_is_xori;
  wire        _dec2_io_is_ori;
  wire        _dec2_io_is_andi;
  wire        _dec2_io_is_slli;
  wire        _dec2_io_is_srli;
  wire        _dec2_io_is_srai;
  wire        _dec2_io_is_add;
  wire        _dec2_io_is_sub;
  wire        _dec2_io_is_sll;
  wire        _dec2_io_is_slt;
  wire        _dec2_io_is_sltu;
  wire        _dec2_io_is_xor;
  wire        _dec2_io_is_srl;
  wire        _dec2_io_is_sra;
  wire        _dec2_io_is_or;
  wire        _dec2_io_is_and;
  wire        _dec2_io_is_csrrw;
  wire        _dec2_io_is_csrrs;
  wire        _dec2_io_is_csrrc;
  wire        _dec2_io_is_csrrwi;
  wire        _dec2_io_is_csrrsi;
  wire        _dec2_io_is_csrrci;
  wire        _dec2_io_is_ecall;
  wire        _dec2_io_is_mret;
  wire        _dec2_io_is_ebreak;
  wire [4:0]  _dec2_io_rd;
  wire [4:0]  _dec2_io_rs1;
  wire [4:0]  _dec2_io_rs2;
  wire [31:0] _dec2_io_imm;
  wire [31:0] _dec2_io_debug_inst;
  wire        _dec1_io_is_jal;
  wire        _dec1_io_is_jalr;
  wire        _dec1_io_is_beq;
  wire        _dec1_io_is_bne;
  wire        _dec1_io_is_blt;
  wire        _dec1_io_is_bge;
  wire        _dec1_io_is_bltu;
  wire        _dec1_io_is_bgeu;
  wire        _dec1_io_is_lb;
  wire        _dec1_io_is_lh;
  wire        _dec1_io_is_lw;
  wire        _dec1_io_is_lbu;
  wire        _dec1_io_is_lhu;
  wire        _dec1_io_is_csrrw;
  wire        _dec1_io_is_csrrs;
  wire        _dec1_io_is_csrrc;
  wire        _dec1_io_is_csrrwi;
  wire        _dec1_io_is_csrrsi;
  wire        _dec1_io_is_csrrci;
  wire        _dec1_io_is_ecall;
  wire        _dec1_io_is_mret;
  wire        _dec1_io_is_ebreak;
  wire [4:0]  _dec1_io_rd;
  wire        isControl1 =
    _dec1_io_is_jal | _dec1_io_is_jalr | _dec1_io_is_beq | _dec1_io_is_bne
    | _dec1_io_is_blt | _dec1_io_is_bge | _dec1_io_is_bltu | _dec1_io_is_bgeu
    | _dec1_io_is_ebreak | _dec1_io_is_csrrw | _dec1_io_is_csrrs | _dec1_io_is_csrrc
    | _dec1_io_is_csrrwi | _dec1_io_is_csrrsi | _dec1_io_is_csrrci | _dec1_io_is_ecall
    | _dec1_io_is_mret;
  wire        final_stall =
    isControl1
    | (_dec1_io_is_lb | _dec1_io_is_lh | _dec1_io_is_lw | _dec1_io_is_lbu
       | _dec1_io_is_lhu) & (|_dec1_io_rd)
    & (_dec1_io_rd == _dec2_io_rs1 | _dec1_io_rd == _dec2_io_rs2) | ~isControl1
    & (_dec2_io_is_jal | _dec2_io_is_jalr | _dec2_io_is_beq | _dec2_io_is_bne
       | _dec2_io_is_blt | _dec2_io_is_bge | _dec2_io_is_bltu | _dec2_io_is_bgeu
       | _dec2_io_is_ebreak | _dec2_io_is_csrrw | _dec2_io_is_csrrs | _dec2_io_is_csrrc
       | _dec2_io_is_csrrwi | _dec2_io_is_csrrsi | _dec2_io_is_csrrci | _dec2_io_is_ecall
       | _dec2_io_is_mret);
  decoder dec1 (
    .io_inst       (io_ifu_to_idu_inst1),
    .io_is_lui     (io_idu_to_exu1_dec1_op_is_lui),
    .io_is_auipc   (io_idu_to_exu1_dec1_op_is_auipc),
    .io_is_jal     (_dec1_io_is_jal),
    .io_is_jalr    (_dec1_io_is_jalr),
    .io_is_beq     (_dec1_io_is_beq),
    .io_is_bne     (_dec1_io_is_bne),
    .io_is_blt     (_dec1_io_is_blt),
    .io_is_bge     (_dec1_io_is_bge),
    .io_is_bltu    (_dec1_io_is_bltu),
    .io_is_bgeu    (_dec1_io_is_bgeu),
    .io_is_lb      (_dec1_io_is_lb),
    .io_is_lh      (_dec1_io_is_lh),
    .io_is_lw      (_dec1_io_is_lw),
    .io_is_lbu     (_dec1_io_is_lbu),
    .io_is_lhu     (_dec1_io_is_lhu),
    .io_is_sb      (io_idu_to_exu1_dec1_op_is_sb),
    .io_is_sh      (io_idu_to_exu1_dec1_op_is_sh),
    .io_is_sw      (io_idu_to_exu1_dec1_op_is_sw),
    .io_is_addi    (io_idu_to_exu1_dec1_op_is_addi),
    .io_is_slti    (io_idu_to_exu1_dec1_op_is_slti),
    .io_is_sltiu   (io_idu_to_exu1_dec1_op_is_sltiu),
    .io_is_xori    (io_idu_to_exu1_dec1_op_is_xori),
    .io_is_ori     (io_idu_to_exu1_dec1_op_is_ori),
    .io_is_andi    (io_idu_to_exu1_dec1_op_is_andi),
    .io_is_slli    (io_idu_to_exu1_dec1_op_is_slli),
    .io_is_srli    (io_idu_to_exu1_dec1_op_is_srli),
    .io_is_srai    (io_idu_to_exu1_dec1_op_is_srai),
    .io_is_add     (io_idu_to_exu1_dec1_op_is_add),
    .io_is_sub     (io_idu_to_exu1_dec1_op_is_sub),
    .io_is_sll     (io_idu_to_exu1_dec1_op_is_sll),
    .io_is_slt     (io_idu_to_exu1_dec1_op_is_slt),
    .io_is_sltu    (io_idu_to_exu1_dec1_op_is_sltu),
    .io_is_xor     (io_idu_to_exu1_dec1_op_is_xor),
    .io_is_srl     (io_idu_to_exu1_dec1_op_is_srl),
    .io_is_sra     (io_idu_to_exu1_dec1_op_is_sra),
    .io_is_or      (io_idu_to_exu1_dec1_op_is_or),
    .io_is_and     (io_idu_to_exu1_dec1_op_is_and),
    .io_is_csrrw   (_dec1_io_is_csrrw),
    .io_is_csrrs   (_dec1_io_is_csrrs),
    .io_is_csrrc   (_dec1_io_is_csrrc),
    .io_is_csrrwi  (_dec1_io_is_csrrwi),
    .io_is_csrrsi  (_dec1_io_is_csrrsi),
    .io_is_csrrci  (_dec1_io_is_csrrci),
    .io_is_ecall   (_dec1_io_is_ecall),
    .io_is_mret    (_dec1_io_is_mret),
    .io_is_ebreak  (_dec1_io_is_ebreak),
    .io_rd         (_dec1_io_rd),
    .io_rs1        (io_idu_to_grf_dec1_redreg_rs1),
    .io_rs2        (io_idu_to_grf_dec1_redreg_rs2),
    .io_imm        (io_idu_to_exu1_dec1_imm),
    .io_debug_inst (io_idu_debug_debug_inst1)
  );
  decoder dec2 (
    .io_inst       (io_ifu_to_idu_inst2),
    .io_is_lui     (_dec2_io_is_lui),
    .io_is_auipc   (_dec2_io_is_auipc),
    .io_is_jal     (_dec2_io_is_jal),
    .io_is_jalr    (_dec2_io_is_jalr),
    .io_is_beq     (_dec2_io_is_beq),
    .io_is_bne     (_dec2_io_is_bne),
    .io_is_blt     (_dec2_io_is_blt),
    .io_is_bge     (_dec2_io_is_bge),
    .io_is_bltu    (_dec2_io_is_bltu),
    .io_is_bgeu    (_dec2_io_is_bgeu),
    .io_is_lb      (_dec2_io_is_lb),
    .io_is_lh      (_dec2_io_is_lh),
    .io_is_lw      (_dec2_io_is_lw),
    .io_is_lbu     (_dec2_io_is_lbu),
    .io_is_lhu     (_dec2_io_is_lhu),
    .io_is_sb      (_dec2_io_is_sb),
    .io_is_sh      (_dec2_io_is_sh),
    .io_is_sw      (_dec2_io_is_sw),
    .io_is_addi    (_dec2_io_is_addi),
    .io_is_slti    (_dec2_io_is_slti),
    .io_is_sltiu   (_dec2_io_is_sltiu),
    .io_is_xori    (_dec2_io_is_xori),
    .io_is_ori     (_dec2_io_is_ori),
    .io_is_andi    (_dec2_io_is_andi),
    .io_is_slli    (_dec2_io_is_slli),
    .io_is_srli    (_dec2_io_is_srli),
    .io_is_srai    (_dec2_io_is_srai),
    .io_is_add     (_dec2_io_is_add),
    .io_is_sub     (_dec2_io_is_sub),
    .io_is_sll     (_dec2_io_is_sll),
    .io_is_slt     (_dec2_io_is_slt),
    .io_is_sltu    (_dec2_io_is_sltu),
    .io_is_xor     (_dec2_io_is_xor),
    .io_is_srl     (_dec2_io_is_srl),
    .io_is_sra     (_dec2_io_is_sra),
    .io_is_or      (_dec2_io_is_or),
    .io_is_and     (_dec2_io_is_and),
    .io_is_csrrw   (_dec2_io_is_csrrw),
    .io_is_csrrs   (_dec2_io_is_csrrs),
    .io_is_csrrc   (_dec2_io_is_csrrc),
    .io_is_csrrwi  (_dec2_io_is_csrrwi),
    .io_is_csrrsi  (_dec2_io_is_csrrsi),
    .io_is_csrrci  (_dec2_io_is_csrrci),
    .io_is_ecall   (_dec2_io_is_ecall),
    .io_is_mret    (_dec2_io_is_mret),
    .io_is_ebreak  (_dec2_io_is_ebreak),
    .io_rd         (_dec2_io_rd),
    .io_rs1        (_dec2_io_rs1),
    .io_rs2        (_dec2_io_rs2),
    .io_imm        (_dec2_io_imm),
    .io_debug_inst (_dec2_io_debug_inst)
  );
  assign io_idu_to_grf_dec2_redreg_rs1 = _dec2_io_rs1;
  assign io_idu_to_grf_dec2_redreg_rs2 = _dec2_io_rs2;
  assign io_idu_to_exu1_dec1_op_is_jal = _dec1_io_is_jal;
  assign io_idu_to_exu1_dec1_op_is_jalr = _dec1_io_is_jalr;
  assign io_idu_to_exu1_dec1_op_is_beq = _dec1_io_is_beq;
  assign io_idu_to_exu1_dec1_op_is_bne = _dec1_io_is_bne;
  assign io_idu_to_exu1_dec1_op_is_blt = _dec1_io_is_blt;
  assign io_idu_to_exu1_dec1_op_is_bge = _dec1_io_is_bge;
  assign io_idu_to_exu1_dec1_op_is_bltu = _dec1_io_is_bltu;
  assign io_idu_to_exu1_dec1_op_is_bgeu = _dec1_io_is_bgeu;
  assign io_idu_to_exu1_dec1_op_is_lb = _dec1_io_is_lb;
  assign io_idu_to_exu1_dec1_op_is_lh = _dec1_io_is_lh;
  assign io_idu_to_exu1_dec1_op_is_lw = _dec1_io_is_lw;
  assign io_idu_to_exu1_dec1_op_is_lbu = _dec1_io_is_lbu;
  assign io_idu_to_exu1_dec1_op_is_lhu = _dec1_io_is_lhu;
  assign io_idu_to_exu1_dec1_op_is_ebreak = _dec1_io_is_ebreak;
  assign io_idu_to_exu1_dec1_val_rs1_val = io_grf_to_idu_dec1_value_inst1rs1_value;
  assign io_idu_to_exu1_dec1_val_rs2_val = io_grf_to_idu_dec1_value_inst1rs2_value;
  assign io_idu_to_exu1_dec1_val_nextpc = io_ifu_to_idu_inst1_nextpc;
  assign io_idu_to_exu1_dec1_rd = _dec1_io_rd;
  assign io_idu_to_exu2_dec2_op_is_lui = ~final_stall & _dec2_io_is_lui;
  assign io_idu_to_exu2_dec2_op_is_auipc = ~final_stall & _dec2_io_is_auipc;
  assign io_idu_to_exu2_dec2_op_is_jal = ~final_stall & _dec2_io_is_jal;
  assign io_idu_to_exu2_dec2_op_is_jalr = ~final_stall & _dec2_io_is_jalr;
  assign io_idu_to_exu2_dec2_op_is_beq = ~final_stall & _dec2_io_is_beq;
  assign io_idu_to_exu2_dec2_op_is_bne = ~final_stall & _dec2_io_is_bne;
  assign io_idu_to_exu2_dec2_op_is_blt = ~final_stall & _dec2_io_is_blt;
  assign io_idu_to_exu2_dec2_op_is_bge = ~final_stall & _dec2_io_is_bge;
  assign io_idu_to_exu2_dec2_op_is_bltu = ~final_stall & _dec2_io_is_bltu;
  assign io_idu_to_exu2_dec2_op_is_bgeu = ~final_stall & _dec2_io_is_bgeu;
  assign io_idu_to_exu2_dec2_op_is_lb = ~final_stall & _dec2_io_is_lb;
  assign io_idu_to_exu2_dec2_op_is_lh = ~final_stall & _dec2_io_is_lh;
  assign io_idu_to_exu2_dec2_op_is_lw = ~final_stall & _dec2_io_is_lw;
  assign io_idu_to_exu2_dec2_op_is_lbu = ~final_stall & _dec2_io_is_lbu;
  assign io_idu_to_exu2_dec2_op_is_lhu = ~final_stall & _dec2_io_is_lhu;
  assign io_idu_to_exu2_dec2_op_is_sb = ~final_stall & _dec2_io_is_sb;
  assign io_idu_to_exu2_dec2_op_is_sh = ~final_stall & _dec2_io_is_sh;
  assign io_idu_to_exu2_dec2_op_is_sw = ~final_stall & _dec2_io_is_sw;
  assign io_idu_to_exu2_dec2_op_is_addi = ~final_stall & _dec2_io_is_addi;
  assign io_idu_to_exu2_dec2_op_is_slti = ~final_stall & _dec2_io_is_slti;
  assign io_idu_to_exu2_dec2_op_is_sltiu = ~final_stall & _dec2_io_is_sltiu;
  assign io_idu_to_exu2_dec2_op_is_xori = ~final_stall & _dec2_io_is_xori;
  assign io_idu_to_exu2_dec2_op_is_ori = ~final_stall & _dec2_io_is_ori;
  assign io_idu_to_exu2_dec2_op_is_andi = ~final_stall & _dec2_io_is_andi;
  assign io_idu_to_exu2_dec2_op_is_slli = ~final_stall & _dec2_io_is_slli;
  assign io_idu_to_exu2_dec2_op_is_srli = ~final_stall & _dec2_io_is_srli;
  assign io_idu_to_exu2_dec2_op_is_srai = ~final_stall & _dec2_io_is_srai;
  assign io_idu_to_exu2_dec2_op_is_add = ~final_stall & _dec2_io_is_add;
  assign io_idu_to_exu2_dec2_op_is_sub = ~final_stall & _dec2_io_is_sub;
  assign io_idu_to_exu2_dec2_op_is_sll = ~final_stall & _dec2_io_is_sll;
  assign io_idu_to_exu2_dec2_op_is_slt = ~final_stall & _dec2_io_is_slt;
  assign io_idu_to_exu2_dec2_op_is_sltu = ~final_stall & _dec2_io_is_sltu;
  assign io_idu_to_exu2_dec2_op_is_xor = ~final_stall & _dec2_io_is_xor;
  assign io_idu_to_exu2_dec2_op_is_srl = ~final_stall & _dec2_io_is_srl;
  assign io_idu_to_exu2_dec2_op_is_sra = ~final_stall & _dec2_io_is_sra;
  assign io_idu_to_exu2_dec2_op_is_or = ~final_stall & _dec2_io_is_or;
  assign io_idu_to_exu2_dec2_op_is_and = ~final_stall & _dec2_io_is_and;
  assign io_idu_to_exu2_dec2_op_is_ebreak = ~final_stall & _dec2_io_is_ebreak;
  assign io_idu_to_exu2_dec2_imm = final_stall ? 32'h0 : _dec2_io_imm;
  assign io_idu_to_exu2_dec2_val_rs1_val =
    final_stall ? 32'h0 : io_grf_to_idu_dec2_value_inst2rs1_value;
  assign io_idu_to_exu2_dec2_val_rs2_val =
    final_stall ? 32'h0 : io_grf_to_idu_dec2_value_inst2rs2_value;
  assign io_idu_to_exu2_dec2_val_nextpc =
    final_stall ? 32'h0 : io_ifu_to_idu_inst2_nextpc;
  assign io_idu_to_exu2_dec2_rd = final_stall ? 5'h0 : _dec2_io_rd;
  assign io_idu_to_ifu_is_stall = final_stall;
  assign io_idu_to_top_is_csrrw = _dec1_io_is_csrrw;
  assign io_idu_to_top_is_csrrs = _dec1_io_is_csrrs;
  assign io_idu_to_top_is_csrrc = _dec1_io_is_csrrc;
  assign io_idu_to_top_is_csrrwi = _dec1_io_is_csrrwi;
  assign io_idu_to_top_is_csrrsi = _dec1_io_is_csrrsi;
  assign io_idu_to_top_is_csrrci = _dec1_io_is_csrrci;
  assign io_idu_to_top_is_ecall = _dec1_io_is_ecall;
  assign io_idu_to_top_is_mret = _dec1_io_is_mret;
  assign io_idu_to_top_is_ebreak = _dec1_io_is_ebreak;
  assign io_idu_to_top_inst1_pc = io_ifu_to_idu_inst1_pc;
  assign io_idu_to_top_inst1 = io_ifu_to_idu_inst1;
  assign io_idu_to_top_rs1_val = io_grf_to_idu_dec1_value_inst1rs1_value;
  assign io_idu_debug_debug_inst2 = final_stall ? 32'h0 : _dec2_io_debug_inst;
  assign io_idu_debug_is_stall = final_stall;
endmodule

