// Generated by CIRCT firtool-1.139.0
module IFU(
  input         clock,
                reset,
                io_take_branch,
  input  [31:0] io_branch_target,
  input         io_is_ebreak,
  output [31:0] io_imemAddr,
                io_pctogrf,
                io_debug_pc,
                io_current_pc
);

  reg  [31:0] pcReg;
  wire [31:0] _pcPlus4_T = pcReg + 32'h4;
  always @(posedge clock) begin
    if (reset)
      pcReg <= 32'h80000000;
    else if (io_is_ebreak) begin
    end
    else
      pcReg <= io_take_branch ? io_branch_target : _pcPlus4_T;
  end // always @(posedge)
  assign io_imemAddr = pcReg;
  assign io_pctogrf = _pcPlus4_T;
  assign io_debug_pc = pcReg;
  assign io_current_pc = pcReg;
endmodule

