// Generated by CIRCT firtool-1.139.0
module IFU(
  input         clock,
                reset,
                io_jalr,
  input  [31:0] io_inputfromBRU,
  output [31:0] io_imemAddr,
                io_pctogrf,
                io_debug_pc
);

  reg  [31:0] pcReg;
  wire [31:0] _currentPcPlus4_T = pcReg + 32'h4;
  always @(posedge clock) begin
    if (reset)
      pcReg <= 32'h80000000;
    else
      pcReg <= io_jalr ? io_inputfromBRU : _currentPcPlus4_T;
  end // always @(posedge)
  assign io_imemAddr = pcReg;
  assign io_pctogrf = _currentPcPlus4_T;
  assign io_debug_pc = pcReg;
endmodule

