// Generated by CIRCT firtool-1.139.0
module imem(
  input         clock,
  input  [31:0] io_ifu_to_imem_addr1,
                io_ifu_to_imem_addr2,
  output [31:0] io_imem_to_ifu_inst1,
                io_imem_to_ifu_inst2
);

  DPI_Memory memory (
    .io_clk (clock),
    .wen    (1'h0),
    .waddr  (32'h0),
    .wdata  (32'h0),
    .wmask  (4'h0),
    .ren1   (1'h1),
    .raddr1 (io_ifu_to_imem_addr1),
    .rdata1 (io_imem_to_ifu_inst1),
    .ren2   (1'h1),
    .raddr2 (io_ifu_to_imem_addr2),
    .rdata2 (io_imem_to_ifu_inst2),
    .ebreak (1'h0)
  );
endmodule

