// Generated by CIRCT firtool-1.139.0
module InformationDecoder(
  input         io_addi,
                io_add,
                io_lui,
                io_jalr,
                io_lbu,
                io_lw,
                io_sw,
                io_sb,
  input  [31:0] io_inst,
  output [4:0]  io_rd,
                io_rs1,
                io_rs2,
  output [31:0] io_imm20,
                io_imm12
);

  wire        _io_rs1_T = io_addi | io_add;
  wire        _io_imm12_T = io_addi | io_jalr;
  wire [11:0] imm12_pre_extended =
    _io_imm12_T | io_lbu | io_lw | io_sw | io_sb
      ? (_io_imm12_T | io_lbu | io_lw ? io_inst[31:20] : {io_inst[31:25], io_inst[11:7]})
      : 12'h0;
  assign io_rd = _io_rs1_T | io_jalr | io_lui | io_lbu | io_lw ? io_inst[11:7] : 5'h0;
  assign io_rs1 =
    _io_rs1_T | io_jalr | io_lbu | io_lw | io_sw | io_sb ? io_inst[19:15] : 5'h0;
  assign io_rs2 = io_add | io_sw | io_sb ? io_inst[24:20] : 5'h0;
  assign io_imm20 = io_lui ? {io_inst[31:12], 12'h0} : 32'h0;
  assign io_imm12 =
    _io_imm12_T | io_lbu | io_lw | io_sw | io_sb
      ? {{20{imm12_pre_extended[11]}}, imm12_pre_extended}
      : 32'h0;
endmodule

