// Generated by CIRCT firtool-1.139.0
module InformationDecoder(
  input         io_is_lui,
                io_is_auipc,
                io_is_jal,
                io_is_jalr,
                io_is_beq,
                io_is_bne,
                io_is_blt,
                io_is_bge,
                io_is_bltu,
                io_is_bgeu,
                io_is_lb,
                io_is_lh,
                io_is_lw,
                io_is_lbu,
                io_is_lhu,
                io_is_sb,
                io_is_sh,
                io_is_sw,
                io_is_addi,
                io_is_slti,
                io_is_sltiu,
                io_is_xori,
                io_is_ori,
                io_is_andi,
                io_is_slli,
                io_is_srli,
                io_is_srai,
                io_is_add,
                io_is_sub,
                io_is_sll,
                io_is_slt,
                io_is_sltu,
                io_is_xor,
                io_is_srl,
                io_is_sra,
                io_is_or,
                io_is_and,
                io_is_csrrw,
                io_is_csrrs,
                io_is_csrrc,
                io_is_csrrwi,
                io_is_csrrsi,
                io_is_csrrci,
  input  [31:0] io_inst,
  output [4:0]  io_rd,
                io_rs1,
                io_rs2,
  output [31:0] io_imm
);

  wire _csr_use_rs1_T = io_is_csrrw | io_is_csrrs;
  wire need_imm_u = io_is_lui | io_is_auipc;
  wire _need_imm_b_T = io_is_beq | io_is_bne;
  assign io_rd =
    need_imm_u | io_is_jal | io_is_jalr | io_is_lb | io_is_lh | io_is_lw | io_is_lbu
    | io_is_lhu | io_is_addi | io_is_slti | io_is_sltiu | io_is_xori | io_is_ori
    | io_is_andi | io_is_slli | io_is_srli | io_is_srai | io_is_add | io_is_sub
    | io_is_sll | io_is_slt | io_is_sltu | io_is_xor | io_is_srl | io_is_sra | io_is_or
    | io_is_and | _csr_use_rs1_T | io_is_csrrc | io_is_csrrwi | io_is_csrrsi
    | io_is_csrrci
      ? io_inst[11:7]
      : 5'h0;
  assign io_rs1 =
    io_is_jalr | io_is_beq | io_is_bne | io_is_blt | io_is_bge | io_is_bltu | io_is_bgeu
    | io_is_lb | io_is_lh | io_is_lw | io_is_lbu | io_is_lhu | io_is_sb | io_is_sh
    | io_is_sw | io_is_addi | io_is_slti | io_is_sltiu | io_is_xori | io_is_ori
    | io_is_andi | io_is_slli | io_is_srli | io_is_srai | io_is_add | io_is_sub
    | io_is_sll | io_is_slt | io_is_sltu | io_is_xor | io_is_srl | io_is_sra | io_is_or
    | io_is_and | _csr_use_rs1_T | io_is_csrrc
      ? io_inst[19:15]
      : 5'h0;
  assign io_rs2 =
    _need_imm_b_T | io_is_blt | io_is_bge | io_is_bltu | io_is_bgeu | io_is_sb | io_is_sh
    | io_is_sw | io_is_add | io_is_sub | io_is_sll | io_is_slt | io_is_sltu | io_is_xor
    | io_is_srl | io_is_sra | io_is_or | io_is_and
      ? io_inst[24:20]
      : 5'h0;
  assign io_imm =
    io_is_jalr | io_is_lb | io_is_lh | io_is_lw | io_is_lbu | io_is_lhu | io_is_addi
    | io_is_slti | io_is_sltiu | io_is_xori | io_is_ori | io_is_andi | io_is_slli
    | io_is_srli | io_is_srai
      ? {{20{io_inst[31]}}, io_inst[31:20]}
      : io_is_sb | io_is_sh | io_is_sw
          ? {{20{io_inst[31]}}, io_inst[31:25], io_inst[11:7]}
          : _need_imm_b_T | io_is_blt | io_is_bge | io_is_bltu | io_is_bgeu
              ? {{20{io_inst[31]}}, io_inst[7], io_inst[30:25], io_inst[11:8], 1'h0}
              : need_imm_u
                  ? {io_inst[31:12], 12'h0}
                  : io_is_jal
                      ? {{12{io_inst[31]}},
                         io_inst[19:12],
                         io_inst[20],
                         io_inst[30:21],
                         1'h0}
                      : 32'h0;
endmodule

