// Generated by CIRCT firtool-1.139.0
module InputMUXforALU(
  input  [31:0] io_inputfromRS1,
                io_inputfromRS2,
                io_inputfromIMM12,
  input         io_add,
                io_addi,
  output [31:0] io_source1,
                io_source2
);

  assign io_source1 = io_add | io_addi ? io_inputfromRS1 : 32'h0;
  assign io_source2 = io_add ? io_inputfromRS2 : io_addi ? io_inputfromIMM12 : 32'h0;
endmodule

