// Generated by CIRCT firtool-1.139.0
module InputMUXforGRF(
  input  io_add,
         io_addi,
         io_jalr,
         io_lbu,
         io_lw,
         io_sw,
         io_sb,
  output io_rs1en,
         io_rs2en
);

  assign io_rs1en = io_addi | io_add | io_jalr | io_lbu | io_lw | io_sw | io_sb;
  assign io_rs2en = io_add | io_sw | io_sb;
endmodule

