// Generated by CIRCT firtool-1.139.0
module InputMUXforALU(
  input  [31:0] io_inputfromRS1,
                io_inputfromRS2,
                io_inputfromIMM,
                io_inputfromU,
                io_current_pc,
  input         io_is_auipc,
                io_use_rs1,
                io_use_rs2,
                io_use_imm_i,
                io_use_u_imm,
  output [31:0] io_source1,
                io_source2
);

  assign io_source1 = io_is_auipc ? io_current_pc : io_use_rs1 ? io_inputfromRS1 : 32'h0;
  assign io_source2 =
    io_use_rs2
      ? io_inputfromRS2
      : io_use_imm_i ? io_inputfromIMM : io_use_u_imm ? io_inputfromU : 32'h0;
endmodule

