// Generated by CIRCT firtool-1.139.0
module InputMUXforAGU(
  input  [31:0] io_inputfromRS1,
                io_inputfromIMM_I,
                io_inputfromIMM_S,
  input         io_is_load,
                io_is_store,
  output [31:0] io_source1,
                io_source2
);

  assign io_source1 = io_is_load | io_is_store ? io_inputfromRS1 : 32'h0;
  assign io_source2 =
    io_is_load ? io_inputfromIMM_I : io_is_store ? io_inputfromIMM_S : 32'h0;
endmodule

