// Generated by CIRCT firtool-1.139.0
module InputMUXforGRF(
  input  io_use_rs1,
         io_use_rs2,
  output io_rs1en,
         io_rs2en
);

  assign io_rs1en = io_use_rs1;
  assign io_rs2en = io_use_rs2;
endmodule

