// Generated by CIRCT firtool-1.139.0
module InputMUXforBRU(
  input  [31:0] io_inputfromRS1,
                io_inputfromIMM12,
  input         io_add,
                io_addi,
                io_jalr,
                io_lbu,
                io_lw,
                io_sw,
                io_sb,
  output [31:0] io_source1,
                io_source2
);

  wire _GEN = io_add | io_addi | io_lbu | io_lw | io_sw | io_sb | ~io_jalr;
  assign io_source1 = _GEN ? 32'h0 : io_inputfromRS1;
  assign io_source2 = _GEN ? 32'h0 : io_inputfromIMM12;
endmodule

