// Generated by CIRCT firtool-1.139.0
module InstructionDecoder(
  input  [31:0] io_inst,
  output        io_is_lui,
                io_is_auipc,
                io_is_jal,
                io_is_jalr,
                io_is_beq,
                io_is_bne,
                io_is_blt,
                io_is_bge,
                io_is_bltu,
                io_is_bgeu,
                io_is_lb,
                io_is_lh,
                io_is_lw,
                io_is_lbu,
                io_is_lhu,
                io_is_sb,
                io_is_sh,
                io_is_sw,
                io_is_addi,
                io_is_slti,
                io_is_sltiu,
                io_is_xori,
                io_is_ori,
                io_is_andi,
                io_is_slli,
                io_is_srli,
                io_is_srai,
                io_is_add,
                io_is_sub,
                io_is_sll,
                io_is_slt,
                io_is_sltu,
                io_is_xor,
                io_is_srl,
                io_is_sra,
                io_is_or,
                io_is_and,
                io_is_ebreak
);

  wire _io_is_ebreak_T_1 = io_inst[14:12] == 3'h0;
  wire _io_is_bgeu_T = io_inst[6:0] == 7'h63;
  wire _io_is_sll_T_1 = io_inst[14:12] == 3'h1;
  wire _io_is_xor_T_1 = io_inst[14:12] == 3'h4;
  wire _io_is_sra_T_1 = io_inst[14:12] == 3'h5;
  wire _io_is_or_T_1 = io_inst[14:12] == 3'h6;
  wire _io_is_lhu_T = io_inst[6:0] == 7'h3;
  wire _io_is_slt_T_1 = io_inst[14:12] == 3'h2;
  wire _io_is_sw_T = io_inst[6:0] == 7'h23;
  wire _io_is_srai_T = io_inst[6:0] == 7'h13;
  wire _io_is_sltu_T_1 = io_inst[14:12] == 3'h3;
  wire _io_is_ebreak_T_9 = io_inst[31:25] == 7'h0;
  wire _io_is_sra_T_3 = io_inst[31:25] == 7'h20;
  wire _io_is_and_T = io_inst[6:0] == 7'h33;
  assign io_is_lui = io_inst[6:0] == 7'h37;
  assign io_is_auipc = io_inst[6:0] == 7'h17;
  assign io_is_jal = io_inst[6:0] == 7'h6F;
  assign io_is_jalr = io_inst[6:0] == 7'h67 & _io_is_ebreak_T_1;
  assign io_is_beq = _io_is_bgeu_T & _io_is_ebreak_T_1;
  assign io_is_bne = _io_is_bgeu_T & _io_is_sll_T_1;
  assign io_is_blt = _io_is_bgeu_T & _io_is_xor_T_1;
  assign io_is_bge = _io_is_bgeu_T & _io_is_sra_T_1;
  assign io_is_bltu = _io_is_bgeu_T & _io_is_or_T_1;
  assign io_is_bgeu = _io_is_bgeu_T & (&(io_inst[14:12]));
  assign io_is_lb = _io_is_lhu_T & _io_is_ebreak_T_1;
  assign io_is_lh = _io_is_lhu_T & _io_is_sll_T_1;
  assign io_is_lw = _io_is_lhu_T & _io_is_slt_T_1;
  assign io_is_lbu = _io_is_lhu_T & _io_is_xor_T_1;
  assign io_is_lhu = _io_is_lhu_T & _io_is_sra_T_1;
  assign io_is_sb = _io_is_sw_T & _io_is_ebreak_T_1;
  assign io_is_sh = _io_is_sw_T & _io_is_sll_T_1;
  assign io_is_sw = _io_is_sw_T & _io_is_slt_T_1;
  assign io_is_addi = _io_is_srai_T & _io_is_ebreak_T_1;
  assign io_is_slti = _io_is_srai_T & _io_is_slt_T_1;
  assign io_is_sltiu = _io_is_srai_T & _io_is_sltu_T_1;
  assign io_is_xori = _io_is_srai_T & _io_is_xor_T_1;
  assign io_is_ori = _io_is_srai_T & _io_is_or_T_1;
  assign io_is_andi = _io_is_srai_T & (&(io_inst[14:12]));
  assign io_is_slli = _io_is_srai_T & _io_is_sll_T_1 & _io_is_ebreak_T_9;
  assign io_is_srli = _io_is_srai_T & _io_is_sra_T_1 & _io_is_ebreak_T_9;
  assign io_is_srai = _io_is_srai_T & _io_is_sra_T_1 & _io_is_sra_T_3;
  assign io_is_add = _io_is_and_T & _io_is_ebreak_T_1 & _io_is_ebreak_T_9;
  assign io_is_sub = _io_is_and_T & _io_is_ebreak_T_1 & _io_is_sra_T_3;
  assign io_is_sll = _io_is_and_T & _io_is_sll_T_1 & _io_is_ebreak_T_9;
  assign io_is_slt = _io_is_and_T & _io_is_slt_T_1 & _io_is_ebreak_T_9;
  assign io_is_sltu = _io_is_and_T & _io_is_sltu_T_1 & _io_is_ebreak_T_9;
  assign io_is_xor = _io_is_and_T & _io_is_xor_T_1 & _io_is_ebreak_T_9;
  assign io_is_srl = _io_is_and_T & _io_is_sra_T_1 & _io_is_ebreak_T_9;
  assign io_is_sra = _io_is_and_T & _io_is_sra_T_1 & _io_is_sra_T_3;
  assign io_is_or = _io_is_and_T & _io_is_or_T_1 & _io_is_ebreak_T_9;
  assign io_is_and = _io_is_and_T & (&(io_inst[14:12])) & _io_is_ebreak_T_9;
  assign io_is_ebreak =
    io_inst[6:0] == 7'h73 & _io_is_ebreak_T_1 & io_inst[19:15] == 5'h0
    & io_inst[11:7] == 5'h0 & _io_is_ebreak_T_9 & (|(io_inst[31:20]));
endmodule

