// Generated by CIRCT firtool-1.139.0
module InstructionDecoder(
  input  [31:0] io_inst,
  output        io_is_addi,
                io_is_add,
                io_is_jalr,
                io_is_lui,
                io_is_lbu,
                io_is_lw,
                io_is_sb,
                io_is_sw,
                io_is_ebreak
);

  wire _io_is_ebreak_T_1 = io_inst[14:12] == 3'h0;
  wire _io_is_ebreak_T_3 = io_inst[31:25] == 7'h0;
  wire _io_is_lw_T = io_inst[6:0] == 7'h3;
  wire _io_is_sw_T_1 = io_inst[14:12] == 3'h2;
  wire _io_is_sw_T = io_inst[6:0] == 7'h23;
  assign io_is_addi = io_inst[6:0] == 7'h13 & _io_is_ebreak_T_1;
  assign io_is_add = io_inst[6:0] == 7'h33 & _io_is_ebreak_T_1 & _io_is_ebreak_T_3;
  assign io_is_jalr = io_inst[6:0] == 7'h67 & _io_is_ebreak_T_1;
  assign io_is_lui = io_inst[6:0] == 7'h37;
  assign io_is_lbu = _io_is_lw_T & io_inst[14:12] == 3'h4;
  assign io_is_lw = _io_is_lw_T & _io_is_sw_T_1;
  assign io_is_sb = _io_is_sw_T & _io_is_ebreak_T_1;
  assign io_is_sw = _io_is_sw_T & _io_is_sw_T_1;
  assign io_is_ebreak =
    io_inst[6:0] == 7'h73 & _io_is_ebreak_T_1 & _io_is_ebreak_T_3 & io_inst[19:15] == 5'h0
    & io_inst[11:7] == 5'h0;
endmodule

