// Generated by CIRCT firtool-1.139.0
module LSU(
  input         io_lw,
                io_lbu,
                io_sw,
                io_sb,
  input  [31:0] io_addr,
                io_wdata,
  output [31:0] io_dmemAddr,
  output        io_dmemWen,
  output [31:0] io_dmemWdata,
  output [3:0]  io_dmemWmask,
  output        io_dmemRen,
  input  [31:0] io_dmemRdata,
  output [31:0] io_rdata
);

  wire [31:0] _byteData_T_1 = io_dmemRdata >> {27'h0, io_addr[1:0], 3'h0};
  assign io_dmemAddr = io_addr;
  assign io_dmemWen = io_sw | io_sb;
  assign io_dmemWdata = io_wdata;
  assign io_dmemWmask = io_sw ? 4'hF : io_sb ? 4'h1 << io_addr[1:0] : 4'h0;
  assign io_dmemRen = io_lw | io_lbu;
  assign io_rdata = io_lw ? io_dmemRdata : io_lbu ? {24'h0, _byteData_T_1[7:0]} : 32'h0;
endmodule

