// Generated by CIRCT firtool-1.139.0
module LSU(
  input         io_exu_to_lsu_op_is_lb,
                io_exu_to_lsu_op_is_lh,
                io_exu_to_lsu_op_is_lw,
                io_exu_to_lsu_op_is_lbu,
                io_exu_to_lsu_op_is_lhu,
                io_exu_to_lsu_op_is_sb,
                io_exu_to_lsu_op_is_sh,
                io_exu_to_lsu_op_is_sw,
                io_exu_to_lsu_op_is_ebreak,
  input  [31:0] io_exu_to_lsu_paddr_addr,
                io_exu_to_lsu_data_store_data,
  input  [4:0]  io_exu_to_lsu_exu_through_lsu_to_wbu_rd,
  input  [31:0] io_exu_to_lsu_exu_through_lsu_to_wbu_grf_wb_data,
  output [31:0] io_lsu_to_dmem_addr,
                io_lsu_to_dmem_store_data,
  output [3:0]  io_lsu_to_dmem_mask,
  output        io_lsu_to_dmem_wen,
                io_lsu_to_dmem_ren,
  input  [31:0] io_dmem_to_lsu_load_data,
  output [4:0]  io_lsu_to_wbu_rd,
  output [31:0] io_lsu_to_wbu_grf_wb_data,
  output        io_ebreak_out,
                io_debug_is_load,
                io_debug_is_store,
  output [31:0] io_debug_addr,
                io_debug_read_origin,
                io_debug_final_wb_data,
  output [3:0]  io_debug_store_mask,
  output [31:0] io_debug_store_data_shifted
);

  wire        is_load =
    io_exu_to_lsu_op_is_lb | io_exu_to_lsu_op_is_lh | io_exu_to_lsu_op_is_lw
    | io_exu_to_lsu_op_is_lbu | io_exu_to_lsu_op_is_lhu;
  wire        is_store =
    io_exu_to_lsu_op_is_sb | io_exu_to_lsu_op_is_sh | io_exu_to_lsu_op_is_sw;
  wire [62:0] _GEN = {31'h0, io_exu_to_lsu_data_store_data};
  wire [62:0] _GEN_0 = {58'h0, io_exu_to_lsu_paddr_addr[1:0], 3'h0};
  wire [62:0] _shifted_wdata_T_1 = _GEN << _GEN_0;
  wire [62:0] _shifted_wdata_T_3 = _GEN << _GEN_0;
  wire [31:0] shifted_wdata =
    io_exu_to_lsu_op_is_sb
      ? _shifted_wdata_T_1[31:0]
      : io_exu_to_lsu_op_is_sh ? _shifted_wdata_T_3[31:0] : io_exu_to_lsu_data_store_data;
  wire [6:0]  _io_lsu_to_dmem_mask_T_4 = 7'h1 << io_exu_to_lsu_paddr_addr[1:0];
  wire [3:0]  _io_lsu_to_dmem_mask_T_7 =
    io_exu_to_lsu_op_is_sw
      ? 4'hF
      : io_exu_to_lsu_op_is_sh
          ? (io_exu_to_lsu_paddr_addr[1:0] == 2'h0
               ? 4'h3
               : io_exu_to_lsu_paddr_addr[1:0] == 2'h2 ? 4'hC : 4'h0)
          : io_exu_to_lsu_op_is_sb ? _io_lsu_to_dmem_mask_T_4[3:0] : 4'h0;
  wire [7:0]  byte_sel =
    io_exu_to_lsu_paddr_addr[1]
      ? (io_exu_to_lsu_paddr_addr[0]
           ? io_dmem_to_lsu_load_data[31:24]
           : io_dmem_to_lsu_load_data[23:16])
      : io_exu_to_lsu_paddr_addr[0]
          ? io_dmem_to_lsu_load_data[15:8]
          : io_dmem_to_lsu_load_data[7:0];
  wire [15:0] half_sel =
    io_exu_to_lsu_paddr_addr[1]
      ? io_dmem_to_lsu_load_data[31:16]
      : io_dmem_to_lsu_load_data[15:0];
  wire [31:0] wb_data =
    is_load
      ? (io_exu_to_lsu_op_is_lw
           ? io_dmem_to_lsu_load_data
           : io_exu_to_lsu_op_is_lh
               ? {{16{half_sel[15]}}, half_sel}
               : io_exu_to_lsu_op_is_lhu
                   ? {16'h0, half_sel}
                   : io_exu_to_lsu_op_is_lb
                       ? {{24{byte_sel[7]}}, byte_sel}
                       : io_exu_to_lsu_op_is_lbu ? {24'h0, byte_sel} : 32'h0)
      : io_exu_to_lsu_exu_through_lsu_to_wbu_grf_wb_data;
  assign io_lsu_to_dmem_addr = {io_exu_to_lsu_paddr_addr[31:2], 2'h0};
  assign io_lsu_to_dmem_store_data = shifted_wdata;
  assign io_lsu_to_dmem_mask = _io_lsu_to_dmem_mask_T_7;
  assign io_lsu_to_dmem_wen = is_store;
  assign io_lsu_to_dmem_ren = is_load;
  assign io_lsu_to_wbu_rd = io_exu_to_lsu_exu_through_lsu_to_wbu_rd;
  assign io_lsu_to_wbu_grf_wb_data = wb_data;
  assign io_ebreak_out = io_exu_to_lsu_op_is_ebreak;
  assign io_debug_is_load = is_load;
  assign io_debug_is_store = is_store;
  assign io_debug_addr = io_exu_to_lsu_paddr_addr;
  assign io_debug_read_origin = io_dmem_to_lsu_load_data;
  assign io_debug_final_wb_data = wb_data;
  assign io_debug_store_mask = _io_lsu_to_dmem_mask_T_7;
  assign io_debug_store_data_shifted = shifted_wdata;
endmodule

