// Generated by CIRCT firtool-1.139.0
module LSU(
  input         io_lb,
                io_lh,
                io_lw,
                io_lbu,
                io_lhu,
                io_sb,
                io_sh,
                io_sw,
  input  [31:0] io_addr,
                io_wdata,
  output [31:0] io_dmemAddr,
  output        io_dmemWen,
  output [31:0] io_dmemWdata,
  output [3:0]  io_dmemWmask,
  output        io_dmemRen,
  input  [31:0] io_dmemRdata,
  output [31:0] io_rdata
);

  wire [62:0] _GEN = {31'h0, io_wdata};
  wire [62:0] _GEN_0 = {58'h0, io_addr[1:0], 3'h0};
  wire [62:0] _shifted_wdata_T_1 = _GEN << _GEN_0;
  wire [62:0] _shifted_wdata_T_3 = _GEN << _GEN_0;
  wire [6:0]  _io_dmemWmask_T_4 = 7'h1 << io_addr[1:0];
  wire [7:0]  byte_sel =
    io_addr[1]
      ? (io_addr[0] ? io_dmemRdata[31:24] : io_dmemRdata[23:16])
      : io_addr[0] ? io_dmemRdata[15:8] : io_dmemRdata[7:0];
  wire [15:0] half_sel = io_addr[1] ? io_dmemRdata[31:16] : io_dmemRdata[15:0];
  assign io_dmemAddr = {io_addr[31:2], 2'h0};
  assign io_dmemWen = io_sb | io_sh | io_sw;
  assign io_dmemWdata =
    io_sb ? _shifted_wdata_T_1[31:0] : io_sh ? _shifted_wdata_T_3[31:0] : io_wdata;
  assign io_dmemWmask =
    io_sw
      ? 4'hF
      : io_sh
          ? (io_addr[1:0] == 2'h0 ? 4'h3 : io_addr[1:0] == 2'h2 ? 4'hC : 4'h0)
          : io_sb ? _io_dmemWmask_T_4[3:0] : 4'h0;
  assign io_dmemRen = io_lb | io_lh | io_lw | io_lbu | io_lhu;
  assign io_rdata =
    io_lw
      ? io_dmemRdata
      : io_lh
          ? {{16{half_sel[15]}}, half_sel}
          : io_lhu
              ? {16'h0, half_sel}
              : io_lb
                  ? {{24{byte_sel[7]}}, byte_sel}
                  : io_lbu ? {24'h0, byte_sel} : 32'h0;
endmodule

