// Generated by CIRCT firtool-1.139.0
module top(
  input         clock,
                reset,
                io_clk,
                io_reset,
  output [31:0] io_debug_pc,
                io_debug_regs_0,
                io_debug_regs_1,
                io_debug_regs_2,
                io_debug_regs_3,
                io_debug_regs_4,
                io_debug_regs_5,
                io_debug_regs_6,
                io_debug_regs_7,
                io_debug_regs_8,
                io_debug_regs_9,
                io_debug_regs_10,
                io_debug_regs_11,
                io_debug_regs_12,
                io_debug_regs_13,
                io_debug_regs_14,
                io_debug_regs_15,
                io_debug_alu_src1,
                io_debug_alu_src2,
                io_debug_alu_res,
  output        io_debug_regWen,
  output [31:0] io_debug_wbData,
  output        io_debug_grf_rden,
  output [4:0]  io_debug_grf_rdaddr,
  output [31:0] io_debug_grf_input,
  output        io_debug_is_add,
                io_debug_is_addi,
                io_debug_is_jalr,
                io_debug_is_lui,
                io_debug_is_lbu,
                io_debug_is_lw,
                io_debug_is_sw,
                io_debug_is_sb,
                io_debug_is_ebreak,
  output [31:0] io_debug_lsu_addr,
  output        io_debug_lsu_wen,
  output [31:0] io_debug_lsu_wdata,
  output [3:0]  io_debug_lsu_wmask,
  output        io_debug_lsu_ren,
  output [31:0] io_debug_lsu_rdata,
                io_debug_inst
);

  wire [31:0] _dataMem_rdata;
  wire [31:0] _instMem_rdata;
  wire [31:0] _csr_io_csr_rdata;
  wire        _csr_io_take_trap;
  wire [31:0] _csr_io_trap_pc;
  wire [31:0] _csr_io_debug_mepc;
  wire [31:0] _grf_io_rs1out;
  wire [31:0] _grf_io_rs2out;
  wire [31:0] _wbu_io_wbData;
  wire        _wbu_io_regWen;
  wire [31:0] _lsu_io_dmemAddr;
  wire        _lsu_io_dmemWen;
  wire [31:0] _lsu_io_dmemWdata;
  wire [3:0]  _lsu_io_dmemWmask;
  wire        _lsu_io_dmemRen;
  wire [31:0] _lsu_io_rdata;
  wire        _exu_io_rs1_en;
  wire        _exu_io_rs2_en;
  wire [31:0] _exu_io_agu_addr;
  wire [31:0] _exu_io_store_data;
  wire [31:0] _exu_io_alu_result;
  wire [4:0]  _exu_io_rd_out;
  wire        _exu_io_take_branch;
  wire [31:0] _exu_io_branch_target;
  wire [4:0]  _exu_io_rs1_addr_out;
  wire [4:0]  _exu_io_rs2_addr_out;
  wire        _idu_io_is_lui;
  wire        _idu_io_is_auipc;
  wire        _idu_io_is_jal;
  wire        _idu_io_is_jalr;
  wire        _idu_io_is_beq;
  wire        _idu_io_is_bne;
  wire        _idu_io_is_blt;
  wire        _idu_io_is_bge;
  wire        _idu_io_is_bltu;
  wire        _idu_io_is_bgeu;
  wire        _idu_io_is_lb;
  wire        _idu_io_is_lh;
  wire        _idu_io_is_lw;
  wire        _idu_io_is_lbu;
  wire        _idu_io_is_lhu;
  wire        _idu_io_is_sb;
  wire        _idu_io_is_sh;
  wire        _idu_io_is_sw;
  wire        _idu_io_is_addi;
  wire        _idu_io_is_slti;
  wire        _idu_io_is_sltiu;
  wire        _idu_io_is_xori;
  wire        _idu_io_is_ori;
  wire        _idu_io_is_andi;
  wire        _idu_io_is_slli;
  wire        _idu_io_is_srli;
  wire        _idu_io_is_srai;
  wire        _idu_io_is_add;
  wire        _idu_io_is_sub;
  wire        _idu_io_is_sll;
  wire        _idu_io_is_slt;
  wire        _idu_io_is_sltu;
  wire        _idu_io_is_xor;
  wire        _idu_io_is_srl;
  wire        _idu_io_is_sra;
  wire        _idu_io_is_or;
  wire        _idu_io_is_and;
  wire        _idu_io_is_csrrw;
  wire        _idu_io_is_csrrs;
  wire        _idu_io_is_csrrc;
  wire        _idu_io_is_csrrwi;
  wire        _idu_io_is_csrrsi;
  wire        _idu_io_is_csrrci;
  wire        _idu_io_is_ecall;
  wire        _idu_io_is_ebreak;
  wire        _idu_io_is_mret;
  wire [4:0]  _idu_io_rd;
  wire [4:0]  _idu_io_rs1;
  wire [4:0]  _idu_io_rs2;
  wire [31:0] _idu_io_imm_i;
  wire [31:0] _idu_io_imm_s;
  wire [31:0] _idu_io_imm_b;
  wire [31:0] _idu_io_imm_u;
  wire [31:0] _idu_io_imm_j;
  wire [31:0] _ifu_io_imemAddr;
  wire [31:0] _ifu_io_pctogrf;
  wire [31:0] _ifu_io_current_pc;
  wire        use_imm_csr = _idu_io_is_csrrwi | _idu_io_is_csrrsi | _idu_io_is_csrrci;
  IFU ifu (
    .clock            (clock),
    .reset            (reset),
    .io_take_branch   (_exu_io_take_branch),
    .io_branch_target (_exu_io_branch_target),
    .io_take_trap     (_csr_io_take_trap),
    .io_trap_pc       (_csr_io_trap_pc),
    .io_take_mret     (_idu_io_is_mret),
    .io_mret_pc       (_csr_io_debug_mepc),
    .io_is_ebreak     (_idu_io_is_ebreak),
    .io_imemAddr      (_ifu_io_imemAddr),
    .io_pctogrf       (_ifu_io_pctogrf),
    .io_debug_pc      (io_debug_pc),
    .io_current_pc    (_ifu_io_current_pc)
  );
  idu idu (
    .io_inst       (_instMem_rdata),
    .io_is_lui     (_idu_io_is_lui),
    .io_is_auipc   (_idu_io_is_auipc),
    .io_is_jal     (_idu_io_is_jal),
    .io_is_jalr    (_idu_io_is_jalr),
    .io_is_beq     (_idu_io_is_beq),
    .io_is_bne     (_idu_io_is_bne),
    .io_is_blt     (_idu_io_is_blt),
    .io_is_bge     (_idu_io_is_bge),
    .io_is_bltu    (_idu_io_is_bltu),
    .io_is_bgeu    (_idu_io_is_bgeu),
    .io_is_lb      (_idu_io_is_lb),
    .io_is_lh      (_idu_io_is_lh),
    .io_is_lw      (_idu_io_is_lw),
    .io_is_lbu     (_idu_io_is_lbu),
    .io_is_lhu     (_idu_io_is_lhu),
    .io_is_sb      (_idu_io_is_sb),
    .io_is_sh      (_idu_io_is_sh),
    .io_is_sw      (_idu_io_is_sw),
    .io_is_addi    (_idu_io_is_addi),
    .io_is_slti    (_idu_io_is_slti),
    .io_is_sltiu   (_idu_io_is_sltiu),
    .io_is_xori    (_idu_io_is_xori),
    .io_is_ori     (_idu_io_is_ori),
    .io_is_andi    (_idu_io_is_andi),
    .io_is_slli    (_idu_io_is_slli),
    .io_is_srli    (_idu_io_is_srli),
    .io_is_srai    (_idu_io_is_srai),
    .io_is_add     (_idu_io_is_add),
    .io_is_sub     (_idu_io_is_sub),
    .io_is_sll     (_idu_io_is_sll),
    .io_is_slt     (_idu_io_is_slt),
    .io_is_sltu    (_idu_io_is_sltu),
    .io_is_xor     (_idu_io_is_xor),
    .io_is_srl     (_idu_io_is_srl),
    .io_is_sra     (_idu_io_is_sra),
    .io_is_or      (_idu_io_is_or),
    .io_is_and     (_idu_io_is_and),
    .io_is_csrrw   (_idu_io_is_csrrw),
    .io_is_csrrs   (_idu_io_is_csrrs),
    .io_is_csrrc   (_idu_io_is_csrrc),
    .io_is_csrrwi  (_idu_io_is_csrrwi),
    .io_is_csrrsi  (_idu_io_is_csrrsi),
    .io_is_csrrci  (_idu_io_is_csrrci),
    .io_is_ecall   (_idu_io_is_ecall),
    .io_is_ebreak  (_idu_io_is_ebreak),
    .io_is_mret    (_idu_io_is_mret),
    .io_rd         (_idu_io_rd),
    .io_rs1        (_idu_io_rs1),
    .io_rs2        (_idu_io_rs2),
    .io_imm_i      (_idu_io_imm_i),
    .io_imm_s      (_idu_io_imm_s),
    .io_imm_b      (_idu_io_imm_b),
    .io_imm_u      (_idu_io_imm_u),
    .io_imm_j      (_idu_io_imm_j),
    .io_debug_inst (io_debug_inst)
  );
  EXU exu (
    .io_is_lui        (_idu_io_is_lui),
    .io_is_auipc      (_idu_io_is_auipc),
    .io_is_jal        (_idu_io_is_jal),
    .io_is_jalr       (_idu_io_is_jalr),
    .io_is_beq        (_idu_io_is_beq),
    .io_is_bne        (_idu_io_is_bne),
    .io_is_blt        (_idu_io_is_blt),
    .io_is_bge        (_idu_io_is_bge),
    .io_is_bltu       (_idu_io_is_bltu),
    .io_is_bgeu       (_idu_io_is_bgeu),
    .io_is_lb         (_idu_io_is_lb),
    .io_is_lh         (_idu_io_is_lh),
    .io_is_lw         (_idu_io_is_lw),
    .io_is_lbu        (_idu_io_is_lbu),
    .io_is_lhu        (_idu_io_is_lhu),
    .io_is_sb         (_idu_io_is_sb),
    .io_is_sh         (_idu_io_is_sh),
    .io_is_sw         (_idu_io_is_sw),
    .io_is_addi       (_idu_io_is_addi),
    .io_is_slti       (_idu_io_is_slti),
    .io_is_sltiu      (_idu_io_is_sltiu),
    .io_is_xori       (_idu_io_is_xori),
    .io_is_ori        (_idu_io_is_ori),
    .io_is_andi       (_idu_io_is_andi),
    .io_is_slli       (_idu_io_is_slli),
    .io_is_srli       (_idu_io_is_srli),
    .io_is_srai       (_idu_io_is_srai),
    .io_is_add        (_idu_io_is_add),
    .io_is_sub        (_idu_io_is_sub),
    .io_is_sll        (_idu_io_is_sll),
    .io_is_slt        (_idu_io_is_slt),
    .io_is_sltu       (_idu_io_is_sltu),
    .io_is_xor        (_idu_io_is_xor),
    .io_is_srl        (_idu_io_is_srl),
    .io_is_sra        (_idu_io_is_sra),
    .io_is_or         (_idu_io_is_or),
    .io_is_and        (_idu_io_is_and),
    .io_rs1_addr      (_idu_io_rs1),
    .io_rs2_addr      (_idu_io_rs2),
    .io_rd_addr       (_idu_io_rd),
    .io_rs1_data      (_grf_io_rs1out),
    .io_rs2_data      (_grf_io_rs2out),
    .io_imm_i         (_idu_io_imm_i),
    .io_imm_s         (_idu_io_imm_s),
    .io_imm_b         (_idu_io_imm_b),
    .io_imm_u         (_idu_io_imm_u),
    .io_imm_j         (_idu_io_imm_j),
    .io_current_pc    (_ifu_io_current_pc),
    .io_rs1_en        (_exu_io_rs1_en),
    .io_rs2_en        (_exu_io_rs2_en),
    .io_agu_addr      (_exu_io_agu_addr),
    .io_store_data    (_exu_io_store_data),
    .io_alu_result    (_exu_io_alu_result),
    .io_rd_out        (_exu_io_rd_out),
    .io_take_branch   (_exu_io_take_branch),
    .io_branch_target (_exu_io_branch_target),
    .io_rs1_addr_out  (_exu_io_rs1_addr_out),
    .io_rs2_addr_out  (_exu_io_rs2_addr_out),
    .io_alu_src1      (io_debug_alu_src1),
    .io_alu_src2      (io_debug_alu_src2)
  );
  LSU lsu (
    .io_lb        (_idu_io_is_lb),
    .io_lh        (_idu_io_is_lh),
    .io_lw        (_idu_io_is_lw),
    .io_lbu       (_idu_io_is_lbu),
    .io_lhu       (_idu_io_is_lhu),
    .io_sb        (_idu_io_is_sb),
    .io_sh        (_idu_io_is_sh),
    .io_sw        (_idu_io_is_sw),
    .io_addr      (_exu_io_agu_addr),
    .io_wdata     (_exu_io_store_data),
    .io_dmemAddr  (_lsu_io_dmemAddr),
    .io_dmemWen   (_lsu_io_dmemWen),
    .io_dmemWdata (_lsu_io_dmemWdata),
    .io_dmemWmask (_lsu_io_dmemWmask),
    .io_dmemRen   (_lsu_io_dmemRen),
    .io_dmemRdata (_dataMem_rdata),
    .io_rdata     (_lsu_io_rdata)
  );
  WBU wbu (
    .io_is_lui       (_idu_io_is_lui),
    .io_is_auipc     (_idu_io_is_auipc),
    .io_is_jal       (_idu_io_is_jal),
    .io_is_jalr      (_idu_io_is_jalr),
    .io_is_lb        (_idu_io_is_lb),
    .io_is_lh        (_idu_io_is_lh),
    .io_is_lw        (_idu_io_is_lw),
    .io_is_lbu       (_idu_io_is_lbu),
    .io_is_lhu       (_idu_io_is_lhu),
    .io_is_addi      (_idu_io_is_addi),
    .io_is_slti      (_idu_io_is_slti),
    .io_is_sltiu     (_idu_io_is_sltiu),
    .io_is_xori      (_idu_io_is_xori),
    .io_is_ori       (_idu_io_is_ori),
    .io_is_andi      (_idu_io_is_andi),
    .io_is_slli      (_idu_io_is_slli),
    .io_is_srli      (_idu_io_is_srli),
    .io_is_srai      (_idu_io_is_srai),
    .io_is_add       (_idu_io_is_add),
    .io_is_sub       (_idu_io_is_sub),
    .io_is_sll       (_idu_io_is_sll),
    .io_is_slt       (_idu_io_is_slt),
    .io_is_sltu      (_idu_io_is_sltu),
    .io_is_xor       (_idu_io_is_xor),
    .io_is_srl       (_idu_io_is_srl),
    .io_is_sra       (_idu_io_is_sra),
    .io_is_or        (_idu_io_is_or),
    .io_is_and       (_idu_io_is_and),
    .io_is_csrrw     (_idu_io_is_csrrw),
    .io_is_csrrs     (_idu_io_is_csrrs),
    .io_is_csrrc     (_idu_io_is_csrrc),
    .io_is_csrrwi    (_idu_io_is_csrrwi),
    .io_is_csrrsi    (_idu_io_is_csrrsi),
    .io_is_csrrci    (_idu_io_is_csrrci),
    .io_inputfromALU (_exu_io_alu_result),
    .io_inputfromPC  (_ifu_io_pctogrf),
    .io_inputfromRAM (_lsu_io_rdata),
    .io_inputfromCSR (_csr_io_csr_rdata),
    .io_wbData       (_wbu_io_wbData),
    .io_regWen       (_wbu_io_regWen),
    .io_debug_regWen (io_debug_regWen),
    .io_debug_wbData (io_debug_wbData)
  );
  GRF grf (
    .clock            (clock),
    .reset            (reset),
    .io_rs1en         (_exu_io_rs1_en),
    .io_rs1addr       (_exu_io_rs1_addr_out),
    .io_rs1out        (_grf_io_rs1out),
    .io_rs2en         (_exu_io_rs2_en),
    .io_rs2addr       (_exu_io_rs2_addr_out),
    .io_rs2out        (_grf_io_rs2out),
    .io_rden          (_wbu_io_regWen),
    .io_rdaddr        (_exu_io_rd_out),
    .io_input         (_wbu_io_wbData),
    .io_debug_regs_0  (io_debug_regs_0),
    .io_debug_regs_1  (io_debug_regs_1),
    .io_debug_regs_2  (io_debug_regs_2),
    .io_debug_regs_3  (io_debug_regs_3),
    .io_debug_regs_4  (io_debug_regs_4),
    .io_debug_regs_5  (io_debug_regs_5),
    .io_debug_regs_6  (io_debug_regs_6),
    .io_debug_regs_7  (io_debug_regs_7),
    .io_debug_regs_8  (io_debug_regs_8),
    .io_debug_regs_9  (io_debug_regs_9),
    .io_debug_regs_10 (io_debug_regs_10),
    .io_debug_regs_11 (io_debug_regs_11),
    .io_debug_regs_12 (io_debug_regs_12),
    .io_debug_regs_13 (io_debug_regs_13),
    .io_debug_regs_14 (io_debug_regs_14),
    .io_debug_regs_15 (io_debug_regs_15),
    .io_debug_rden    (io_debug_grf_rden),
    .io_debug_rdaddr  (io_debug_grf_rdaddr),
    .io_debug_input   (io_debug_grf_input)
  );
  CSR csr (
    .clock          (clock),
    .reset          (reset),
    .io_csr_addr    (_instMem_rdata[31:20]),
    .io_csr_rdata   (_csr_io_csr_rdata),
    .io_csr_wen
      ((_idu_io_is_csrrw | _idu_io_is_csrrs | _idu_io_is_csrrc | _idu_io_is_csrrwi
        | _idu_io_is_csrrsi | _idu_io_is_csrrci)
       & (_idu_io_is_csrrw | _idu_io_is_csrrwi
          | (use_imm_csr ? (|(_instMem_rdata[19:15])) : (|_idu_io_rs1)))),
    .io_csr_waddr   (_instMem_rdata[31:20]),
    .io_csr_op
      (_idu_io_is_csrrs | _idu_io_is_csrrsi
         ? 3'h1
         : {1'h0, _idu_io_is_csrrc | _idu_io_is_csrrci, 1'h0}),
    .io_rs1_val     (_grf_io_rs1out),
    .io_use_imm     (use_imm_csr),
    .io_ecall       (_idu_io_is_ecall),
    .io_is_ebreak   (_idu_io_is_ebreak),
    .io_current_pc  (_ifu_io_current_pc),
    .io_take_trap   (_csr_io_take_trap),
    .io_trap_pc     (_csr_io_trap_pc),
    .io_inst_retire (~_idu_io_is_ebreak & ~_idu_io_is_ecall),
    .io_debug_mepc  (_csr_io_debug_mepc)
  );
  DPI_Memory instMem (
    .io_clk (clock),
    .wen    (1'h0),
    .waddr  (32'h0),
    .wdata  (32'h0),
    .wmask  (4'h0),
    .ren    (1'h1),
    .raddr  (_ifu_io_imemAddr),
    .rdata  (_instMem_rdata),
    .ebreak (_idu_io_is_ebreak)
  );
  DPI_Memory dataMem (
    .io_clk (clock),
    .wen    (_lsu_io_dmemWen),
    .waddr  (_lsu_io_dmemAddr),
    .wdata  (_lsu_io_dmemWdata),
    .wmask  (_lsu_io_dmemWmask),
    .ren    (_lsu_io_dmemRen),
    .raddr  (_lsu_io_dmemAddr),
    .rdata  (_dataMem_rdata),
    .ebreak (_idu_io_is_ebreak)
  );
  assign io_debug_alu_res = _exu_io_alu_result;
  assign io_debug_is_add = _idu_io_is_add;
  assign io_debug_is_addi = _idu_io_is_addi;
  assign io_debug_is_jalr = _idu_io_is_jalr;
  assign io_debug_is_lui = _idu_io_is_lui;
  assign io_debug_is_lbu = _idu_io_is_lbu;
  assign io_debug_is_lw = _idu_io_is_lw;
  assign io_debug_is_sw = _idu_io_is_sw;
  assign io_debug_is_sb = _idu_io_is_sb;
  assign io_debug_is_ebreak = _idu_io_is_ebreak;
  assign io_debug_lsu_addr = _lsu_io_dmemAddr;
  assign io_debug_lsu_wen = _lsu_io_dmemWen;
  assign io_debug_lsu_wdata = _lsu_io_dmemWdata;
  assign io_debug_lsu_wmask = _lsu_io_dmemWmask;
  assign io_debug_lsu_ren = _lsu_io_dmemRen;
  assign io_debug_lsu_rdata = _dataMem_rdata;
endmodule

