// Generated by CIRCT firtool-1.139.0
module WBU(
  input         io_add,
                io_addi,
                io_jalr,
                io_lbu,
                io_lw,
                io_lui,
  input  [31:0] io_inputfromALU,
                io_inputfromPC,
                io_inputfromRAM,
                io_inputfromIDU,
  output [31:0] io_wbData,
  output        io_regWen
);

  wire _io_regWen_T = io_add | io_addi;
  assign io_wbData =
    _io_regWen_T
      ? io_inputfromALU
      : io_jalr
          ? io_inputfromPC
          : io_lbu | io_lw ? io_inputfromRAM : io_lui ? io_inputfromIDU : 32'h0;
  assign io_regWen = _io_regWen_T | io_jalr | io_lbu | io_lw | io_lui;
endmodule

