// Generated by CIRCT firtool-1.139.0
module wbu(
  output [4:0]  io_wbu_to_grf_wr1_addr,
  output [31:0] io_wbu_to_grf_wr1_data,
  output [4:0]  io_wbu_to_grf_wr2_addr,
  output [31:0] io_wbu_to_grf_wr2_data,
  input  [4:0]  io_lsu_to_wbu_1_rd,
  input  [31:0] io_lsu_to_wbu_1_grf_wb_data,
  input  [4:0]  io_lsu_to_wbu_2_rd,
  input  [31:0] io_lsu_to_wbu_2_grf_wb_data,
  output        io_debug_valid1,
                io_debug_valid2,
                io_debug_conflict,
  output [4:0]  io_debug_rd1,
                io_debug_rd2,
                io_debug_wr1_addr,
                io_debug_wr2_addr
);

  wire       conflict =
    (|io_lsu_to_wbu_1_rd) & (|io_lsu_to_wbu_2_rd)
    & io_lsu_to_wbu_1_rd == io_lsu_to_wbu_2_rd;
  wire [4:0] io_debug_wr2_addr_0 = (|io_lsu_to_wbu_2_rd) ? io_lsu_to_wbu_2_rd : 5'h0;
  wire [4:0] io_debug_wr1_addr_0 =
    (|io_lsu_to_wbu_1_rd) & ~conflict ? io_lsu_to_wbu_1_rd : 5'h0;
  assign io_wbu_to_grf_wr1_addr = io_debug_wr1_addr_0;
  assign io_wbu_to_grf_wr1_data = io_lsu_to_wbu_1_grf_wb_data;
  assign io_wbu_to_grf_wr2_addr = io_debug_wr2_addr_0;
  assign io_wbu_to_grf_wr2_data = io_lsu_to_wbu_2_grf_wb_data;
  assign io_debug_valid1 = |io_lsu_to_wbu_1_rd;
  assign io_debug_valid2 = |io_lsu_to_wbu_2_rd;
  assign io_debug_conflict = conflict;
  assign io_debug_rd1 = io_lsu_to_wbu_1_rd;
  assign io_debug_rd2 = io_lsu_to_wbu_2_rd;
  assign io_debug_wr1_addr = io_debug_wr1_addr_0;
  assign io_debug_wr2_addr = io_debug_wr2_addr_0;
endmodule

