// Generated by CIRCT firtool-1.139.0
module WBU(
  input         io_add,
                io_addi,
                io_jalr,
                io_lbu,
                io_lw,
                io_lui,
  input  [31:0] io_inputfromALU,
                io_inputfromPC,
                io_inputfromRAM,
                io_inputfromIDU,
  output [31:0] io_wbData,
  output        io_regWen,
                io_debug_regWen,
  output [31:0] io_debug_wbData
);

  wire        _io_regWen_T = io_add | io_addi;
  wire [31:0] io_wbData_0 =
    _io_regWen_T
      ? io_inputfromALU
      : io_jalr
          ? io_inputfromPC
          : io_lbu | io_lw ? io_inputfromRAM : io_lui ? io_inputfromIDU : 32'h0;
  wire        io_regWen_0 = _io_regWen_T | io_jalr | io_lbu | io_lw | io_lui;
  assign io_wbData = io_wbData_0;
  assign io_regWen = io_regWen_0;
  assign io_debug_regWen = io_regWen_0;
  assign io_debug_wbData = io_wbData_0;
endmodule

