// Generated by CIRCT firtool-1.139.0
module WBU(
  input         io_is_lui,
                io_is_auipc,
                io_is_jal,
                io_is_jalr,
                io_is_lb,
                io_is_lh,
                io_is_lw,
                io_is_lbu,
                io_is_lhu,
                io_is_addi,
                io_is_slti,
                io_is_sltiu,
                io_is_xori,
                io_is_ori,
                io_is_andi,
                io_is_slli,
                io_is_srli,
                io_is_srai,
                io_is_add,
                io_is_sub,
                io_is_sll,
                io_is_slt,
                io_is_sltu,
                io_is_xor,
                io_is_srl,
                io_is_sra,
                io_is_or,
                io_is_and,
                io_is_csrrw,
                io_is_csrrs,
                io_is_csrrc,
                io_is_csrrwi,
                io_is_csrrsi,
                io_is_csrrci,
  input  [31:0] io_inputfromALU,
                io_inputfromPC,
                io_inputfromRAM,
                io_inputfromCSR,
  output [31:0] io_wbData,
  output        io_regWen,
                io_debug_regWen,
  output [31:0] io_debug_wbData
);

  wire        need_wb =
    io_is_lui | io_is_auipc | io_is_jal | io_is_jalr | io_is_lb | io_is_lh | io_is_lw
    | io_is_lbu | io_is_lhu | io_is_addi | io_is_slti | io_is_sltiu | io_is_xori
    | io_is_ori | io_is_andi | io_is_slli | io_is_srli | io_is_srai | io_is_add
    | io_is_sub | io_is_sll | io_is_slt | io_is_sltu | io_is_xor | io_is_srl | io_is_sra
    | io_is_or | io_is_and | io_is_csrrw | io_is_csrrs | io_is_csrrc | io_is_csrrwi
    | io_is_csrrsi | io_is_csrrci;
  wire [31:0] io_wbData_0 =
    io_is_csrrw | io_is_csrrs | io_is_csrrc | io_is_csrrwi | io_is_csrrsi | io_is_csrrci
      ? io_inputfromCSR
      : io_is_lui | io_is_auipc
          ? io_inputfromALU
          : io_is_jal | io_is_jalr
              ? io_inputfromPC
              : io_is_lb | io_is_lh | io_is_lw | io_is_lbu | io_is_lhu
                  ? io_inputfromRAM
                  : io_is_addi | io_is_slti | io_is_sltiu | io_is_xori | io_is_ori
                    | io_is_andi | io_is_slli | io_is_srli | io_is_srai | io_is_add
                    | io_is_sub | io_is_sll | io_is_slt | io_is_sltu | io_is_xor
                    | io_is_srl | io_is_sra | io_is_or | io_is_and
                      ? io_inputfromALU
                      : 32'h0;
  assign io_wbData = io_wbData_0;
  assign io_regWen = need_wb;
  assign io_debug_regWen = need_wb;
  assign io_debug_wbData = io_wbData_0;
endmodule

